/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.component.huggingface.springboot;

import org.apache.camel.component.huggingface.HuggingFaceConfiguration;
import org.apache.camel.spring.boot.ComponentConfigurationPropertiesCommon;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Integration with Hugging Face's Model Hub by using the Deep Java Library
 * (DJL) Python bridge
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "camel.component.huggingface")
public class HuggingFaceComponentConfiguration
        extends
            ComponentConfigurationPropertiesCommon {

    /**
     * Whether to enable auto configuration of the huggingface component. This
     * is enabled by default.
     */
    private Boolean enabled;
    /**
     * HF API token for private models
     */
    private String authToken;
    /**
     * If true, auto-select the best label (highest score) for zero-shot
     * classification
     */
    private Boolean autoSelect = true;
    /**
     * The configuration. The option is a
     * org.apache.camel.component.huggingface.HuggingFaceConfiguration type.
     */
    private HuggingFaceConfiguration configuration;
    /**
     * Device for inference (cpu, gpu, auto)
     */
    private String device;
    /**
     * Whether the producer should be started lazy (on the first message). By
     * starting lazy you can use this to allow CamelContext and routes to
     * startup in situations where a producer may otherwise fail during starting
     * and cause the route to fail being started. By deferring this startup to
     * be lazy then the startup failure can be handled during routing messages
     * via Camel's routing error handlers. Beware that when the first message is
     * processed then creating and starting the producer may take a little time
     * and prolong the total processing time of the processing.
     */
    private Boolean lazyStartProducer = false;
    /**
     * Max tokens for generation tasks
     */
    private Integer maxTokens;
    /**
     * Header name for conversation memory ID (for multi-user chats)
     */
    private String memoryIdHeader = "CamelChatMemoryId";
    /**
     * Min tokens for summarization tasks
     */
    private Integer minLength;
    /**
     * Hugging Face model ID (e.g.,
     * distilbert-base-uncased-finetuned-sst-2-english)
     */
    private String modelId;
    /**
     * Model loading timeout in seconds, if negative then use default (240
     * seconds)
     */
    private Integer modelLoadingTimeout;
    /**
     * Allow multi-label classifications for zero-shot tasks
     */
    private Boolean multiLabel = false;
    /**
     * Bean name of a custom TaskPredictor implementation (for tasks not covered
     * by built-in predictors)
     */
    private String predictorBean;
    /**
     * Predict timeout in seconds, if negative then use default (120 seconds)
     */
    private Integer predictTimeout;
    /**
     * Model revision or branch (default: main)
     */
    private String revision;
    /**
     * Initial system prompt for chat tasks (e.g., 'You are a helpful assistant
     * named Alan.')
     */
    private String systemPrompt;
    /**
     * Temperature for sampling (0.0-1.0)
     */
    private Float temperature;
    /**
     * Top-k parameter for classification tasks
     */
    private Integer topK = 5;
    /**
     * Role for user messages in chat history (e.g., 'user' or 'human')
     */
    private String userRole = "user";
    /**
     * Whether autowiring is enabled. This is used for automatic autowiring
     * options (the option must be marked as autowired) by looking up in the
     * registry to find if there is a single instance of matching type, which
     * then gets configured on the component. This can be used for automatic
     * configuring JDBC data sources, JMS connection factories, AWS Clients,
     * etc.
     */
    private Boolean autowiredEnabled = true;
    /**
     * Used for enabling or disabling all consumer based health checks from this
     * component
     */
    private Boolean healthCheckConsumerEnabled = true;
    /**
     * Used for enabling or disabling all producer based health checks from this
     * component. Notice: Camel has by default disabled all producer based
     * health-checks. You can turn on producer checks globally by setting
     * camel.health.producersEnabled=true.
     */
    private Boolean healthCheckProducerEnabled = true;
    /**
     * OAuth profile name for obtaining an access token via the OAuth 2.0 Client
     * Credentials grant. When set, the token is acquired from the configured
     * identity provider and used as authToken. Requires camel-oauth on the
     * classpath.
     */
    private String oauthProfile;

    public String getAuthToken() {
        return authToken;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    public Boolean getAutoSelect() {
        return autoSelect;
    }

    public void setAutoSelect(Boolean autoSelect) {
        this.autoSelect = autoSelect;
    }

    public HuggingFaceConfiguration getConfiguration() {
        return configuration;
    }

    public void setConfiguration(HuggingFaceConfiguration configuration) {
        this.configuration = configuration;
    }

    public String getDevice() {
        return device;
    }

    public void setDevice(String device) {
        this.device = device;
    }

    public Boolean getLazyStartProducer() {
        return lazyStartProducer;
    }

    public void setLazyStartProducer(Boolean lazyStartProducer) {
        this.lazyStartProducer = lazyStartProducer;
    }

    public Integer getMaxTokens() {
        return maxTokens;
    }

    public void setMaxTokens(Integer maxTokens) {
        this.maxTokens = maxTokens;
    }

    public String getMemoryIdHeader() {
        return memoryIdHeader;
    }

    public void setMemoryIdHeader(String memoryIdHeader) {
        this.memoryIdHeader = memoryIdHeader;
    }

    public Integer getMinLength() {
        return minLength;
    }

    public void setMinLength(Integer minLength) {
        this.minLength = minLength;
    }

    public String getModelId() {
        return modelId;
    }

    public void setModelId(String modelId) {
        this.modelId = modelId;
    }

    public Integer getModelLoadingTimeout() {
        return modelLoadingTimeout;
    }

    public void setModelLoadingTimeout(Integer modelLoadingTimeout) {
        this.modelLoadingTimeout = modelLoadingTimeout;
    }

    public Boolean getMultiLabel() {
        return multiLabel;
    }

    public void setMultiLabel(Boolean multiLabel) {
        this.multiLabel = multiLabel;
    }

    public String getPredictorBean() {
        return predictorBean;
    }

    public void setPredictorBean(String predictorBean) {
        this.predictorBean = predictorBean;
    }

    public Integer getPredictTimeout() {
        return predictTimeout;
    }

    public void setPredictTimeout(Integer predictTimeout) {
        this.predictTimeout = predictTimeout;
    }

    public String getRevision() {
        return revision;
    }

    public void setRevision(String revision) {
        this.revision = revision;
    }

    public String getSystemPrompt() {
        return systemPrompt;
    }

    public void setSystemPrompt(String systemPrompt) {
        this.systemPrompt = systemPrompt;
    }

    public Float getTemperature() {
        return temperature;
    }

    public void setTemperature(Float temperature) {
        this.temperature = temperature;
    }

    public Integer getTopK() {
        return topK;
    }

    public void setTopK(Integer topK) {
        this.topK = topK;
    }

    public String getUserRole() {
        return userRole;
    }

    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    public Boolean getAutowiredEnabled() {
        return autowiredEnabled;
    }

    public void setAutowiredEnabled(Boolean autowiredEnabled) {
        this.autowiredEnabled = autowiredEnabled;
    }

    public Boolean getHealthCheckConsumerEnabled() {
        return healthCheckConsumerEnabled;
    }

    public void setHealthCheckConsumerEnabled(Boolean healthCheckConsumerEnabled) {
        this.healthCheckConsumerEnabled = healthCheckConsumerEnabled;
    }

    public Boolean getHealthCheckProducerEnabled() {
        return healthCheckProducerEnabled;
    }

    public void setHealthCheckProducerEnabled(Boolean healthCheckProducerEnabled) {
        this.healthCheckProducerEnabled = healthCheckProducerEnabled;
    }

    public String getOauthProfile() {
        return oauthProfile;
    }

    public void setOauthProfile(String oauthProfile) {
        this.oauthProfile = oauthProfile;
    }
}