<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.apache.camel.springboot</groupId>
    <artifactId>camel-sap-starter-parent</artifactId>
    <version>4.22.0-SNAPSHOT</version>
  </parent>
  <groupId>org.fusesource</groupId>
  <artifactId>camel-sap-starter</artifactId>
  <packaging>jar</packaging>
  <name>JBoss Fuse :: Components :: SAP JCO :: Spring-Boot Starter</name>
  <description>SAP Camel Componet Spring Boot Starter</description>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <sapjco3-version>3.1.4</sapjco3-version>
    <sapidoc3-version>3.1.1</sapidoc3-version>
    <lib.directory>${project.build.directory}/lib</lib.directory>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
      <version>${spring-boot-version}</version>
    </dependency>
    <dependency>
      <groupId>org.fusesource</groupId>
      <artifactId>camel-sap</artifactId>
      <version>${camel-sap.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-support</artifactId>
      <version>${camel-version}</version>
    </dependency>


    <!-- JCO jars -->

    <dependency>
      <groupId>com.sap.conn.jco</groupId>
      <artifactId>sapjco3</artifactId>
      <version>${sapjco3-version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sap.conn.idoc</groupId>
      <artifactId>sapidoc3</artifactId>
      <version>${sapidoc3-version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <!--START OF GENERATED CODE-->
    <dependency>
      <groupId>org.apache.camel.springboot</groupId>
      <artifactId>camel-core-starter</artifactId>
    </dependency>
    <!--END OF GENERATED CODE-->
  </dependencies>
  <build>
    <defaultGoal>install</defaultGoal>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.0.1</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <phase>process-classes</phase>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-jco-idoc-libs</id>
            <phase>validate</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <stripVersion>true</stripVersion>
              <outputDirectory>${lib.directory}</outputDirectory>
              <artifactItems>
                <artifactItem>
                  <groupId>com.sap.conn.jco</groupId>
                  <artifactId>sapjco3</artifactId>
                  <overWrite>true</overWrite>
                  <destFileName>sapjco3.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.sap.conn.idoc</groupId>
                  <artifactId>sapidoc3</artifactId>
                  <overWrite>true</overWrite>
                  <destFileName>sapidoc3.jar</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <pluginManagement />
  </build>
  <distributionManagement>
    <repository>
      <id>jboss-releases-repository</id>
      <name>JBoss Releases Repository</name>
      <url>https://repository.jboss.org/nexus/service/local/staging/deploy/maven2</url>
    </repository>
    <snapshotRepository>
      <id>jboss-snapshots-repository</id>
      <name>JBoss Snapshots Repository</name>
      <url>https://repository.jboss.org/nexus/content/repositories/snapshots</url>
    </snapshotRepository>
  </distributionManagement>
  <profiles>
    <profile>
      <id>regen</id>
      <build>
        <plugins>
          <plugin>
            <!-- This is copy-pasted from the components-starter pom. Ideally this should be inherited like the other
            starters.
            -->
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-spring-boot-generator-maven-plugin</artifactId>
            <version>${project.version}</version>
            <configuration>
              <!-- set to true to make build fail fast if missing documentation in docs files -->
              <failFast>false</failFast>
              <!-- set to true to make build fail if an option has no description -->
              <failOnMissingDescription>false</failOnMissingDescription>
            </configuration>
            <executions>
              <execution>
                <id>generate</id>
                <goals>
                  <goal>prepare-spring-boot-starter</goal>
                  <goal>prepare-spring-boot-auto-configuration</goal>
                  <goal>prepare-catalog-springboot</goal>
                </goals>
                <phase>generate-resources</phase>
              </execution>
              <execution>
                <id>readme</id>
                <goals>
                  <goal>update-spring-boot-auto-configuration-readme</goal>
                </goals>
                <phase>package</phase>
              </execution>
            </executions>
          </plugin>
          <!-- This is somehow needed by the camel-spring-boot-generator-maven-plugin that is trying to resolve camel-sap's system path dependencies. Needs to be investigated further.-->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <id>copy-jco-idoc-libs-system-path</id>
                <phase>validate</phase>
                <goals>
                  <goal>copy</goal>
                </goals>
                <configuration>
                  <stripVersion>true</stripVersion>
                  <outputDirectory>/tmp/fuse-components-3.20.1/camel-sap/camel-sap-component/target/lib</outputDirectory>
                  <artifactItems>
                    <artifactItem>
                      <groupId>com.sap.conn.jco</groupId>
                      <artifactId>sapjco3</artifactId>
                      <overWrite>true</overWrite>
                      <destFileName>sapjco3.jar</destFileName>
                    </artifactItem>
                    <artifactItem>
                      <groupId>com.sap.conn.idoc</groupId>
                      <artifactId>sapidoc3</artifactId>
                      <overWrite>true</overWrite>
                      <destFileName>sapidoc3.jar</destFileName>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
  <!--START OF GENERATED CODE-->
  <repositories>
    <repository>
      <id>fusesource-third-party-internal</id>
      <url>https://repository.jboss.org/nexus/content/repositories/fs-releases/</url>
      <layout>default</layout>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>brewroot</id>
      <name>Brew Repository</name>
      <url>http://download.eng.bos.redhat.com/brewroot/repos/jb-fuse-6.2-build/latest/maven</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>never</updatePolicy>
      </releases>
    </repository>
    <repository>
      <id>jboss-ea</id>
      <name>Fuse Early Access Repository</name>
      <url>https://repository.jboss.org/nexus/content/groups/ea</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>redhat-ga-repository</id>
      <url>https://maven.repository.redhat.com/ga</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>
  <!--END OF GENERATED CODE-->
</project>
