/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.component.openfeature.springboot;

import org.apache.camel.component.openfeature.OpenFeatureConfiguration;
import org.apache.camel.spring.boot.ComponentConfigurationPropertiesCommon;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Evaluate feature flags using the OpenFeature specification with flagd.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "camel.component.openfeature")
public class OpenFeatureComponentConfiguration
        extends
            ComponentConfigurationPropertiesCommon {

    /**
     * Whether to enable auto configuration of the openfeature component. This
     * is enabled by default.
     */
    private Boolean enabled;
    /**
     * Default configuration shared by OpenFeature endpoints. The option is a
     * org.apache.camel.component.openfeature.OpenFeatureConfiguration type.
     */
    private OpenFeatureConfiguration configuration;
    /**
     * When true, a Map message body is used as the evaluation context. When
     * false (default), the body is not used as context. The
     * CamelOpenFeatureEvaluationContext header is always used regardless of
     * this setting.
     */
    private Boolean contextFromBody = false;
    /**
     * Deadline in milliseconds for the remote flagd connection.
     */
    private Integer deadline = 500;
    /**
     * Default value when flag evaluation fails. When evaluationType is not set,
     * also determines the evaluation type: true or false (case-insensitive)
     * selects boolean evaluation, any other value selects string evaluation.
     */
    private String defaultValue = "false";
    /**
     * The evaluation type. 'boolean' and 'isEnabled' use boolean evaluation
     * (getBooleanValue). 'variant' uses string evaluation (getStringValue).
     * When not set, the type is inferred from defaultValue. Can also be set as
     * a path parameter in the endpoint URI, which takes precedence.
     */
    private String evaluationType;
    /**
     * The feature flag key to evaluate. Can be overridden per message via the
     * CamelOpenFeatureFlagKey header.
     */
    private String flagKey;
    /**
     * A JSON object defining feature flags in flagd format (inline). Mutually
     * exclusive with flagsResource.
     */
    private String flags;
    /**
     * Camel resource URI pointing to a feature flag definition file in flagd
     * format. Mutually exclusive with flags. When provider is also set, the
     * provider takes precedence.
     */
    private String flagsResource;
    /**
     * Remote flagd service host. When set, the flagd RPC resolver is used.
     */
    private String host;
    /**
     * Remote flagd service port.
     */
    private Integer port = 8013;
    /**
     * Bean reference to a custom FeatureProvider (e.g. #myProvider). When set,
     * takes precedence over flags, flagsResource, and host.
     */
    private String provider;
    /**
     * Whether the producer should be started lazy (on the first message). By
     * starting lazy you can use this to allow CamelContext and routes to
     * startup in situations where a producer may otherwise fail during starting
     * and cause the route to fail being started. By deferring this startup to
     * be lazy then the startup failure can be handled during routing messages
     * via Camel's routing error handlers. Beware that when the first message is
     * processed then creating and starting the producer may take a little time
     * and prolong the total processing time of the processing.
     */
    private Boolean lazyStartProducer = false;
    /**
     * Store the evaluation result in this exchange property, preserving the
     * original message body.
     */
    private String resultProperty;
    /**
     * Whether autowiring is enabled. This is used for automatic autowiring
     * options (the option must be marked as autowired) by looking up in the
     * registry to find if there is a single instance of matching type, which
     * then gets configured on the component. This can be used for automatic
     * configuring JDBC data sources, JMS connection factories, AWS Clients,
     * etc.
     */
    private Boolean autowiredEnabled = true;
    /**
     * Path to the TLS certificate for the remote flagd connection.
     */
    private String certPath;
    /**
     * Whether to use TLS for the remote flagd connection.
     */
    private Boolean tls = false;

    public OpenFeatureConfiguration getConfiguration() {
        return configuration;
    }

    public void setConfiguration(OpenFeatureConfiguration configuration) {
        this.configuration = configuration;
    }

    public Boolean getContextFromBody() {
        return contextFromBody;
    }

    public void setContextFromBody(Boolean contextFromBody) {
        this.contextFromBody = contextFromBody;
    }

    public Integer getDeadline() {
        return deadline;
    }

    public void setDeadline(Integer deadline) {
        this.deadline = deadline;
    }

    public String getDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    public String getEvaluationType() {
        return evaluationType;
    }

    public void setEvaluationType(String evaluationType) {
        this.evaluationType = evaluationType;
    }

    public String getFlagKey() {
        return flagKey;
    }

    public void setFlagKey(String flagKey) {
        this.flagKey = flagKey;
    }

    public String getFlags() {
        return flags;
    }

    public void setFlags(String flags) {
        this.flags = flags;
    }

    public String getFlagsResource() {
        return flagsResource;
    }

    public void setFlagsResource(String flagsResource) {
        this.flagsResource = flagsResource;
    }

    public String getHost() {
        return host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public Integer getPort() {
        return port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public Boolean getLazyStartProducer() {
        return lazyStartProducer;
    }

    public void setLazyStartProducer(Boolean lazyStartProducer) {
        this.lazyStartProducer = lazyStartProducer;
    }

    public String getResultProperty() {
        return resultProperty;
    }

    public void setResultProperty(String resultProperty) {
        this.resultProperty = resultProperty;
    }

    public Boolean getAutowiredEnabled() {
        return autowiredEnabled;
    }

    public void setAutowiredEnabled(Boolean autowiredEnabled) {
        this.autowiredEnabled = autowiredEnabled;
    }

    public String getCertPath() {
        return certPath;
    }

    public void setCertPath(String certPath) {
        this.certPath = certPath;
    }

    public Boolean getTls() {
        return tls;
    }

    public void setTls(Boolean tls) {
        this.tls = tls;
    }
}