== Camel Example with Elytron

=== Introduction

This example demonstrates how you can use Camel-Elytron Starter component. The example is simple. One route exposes url endpoint with restriction to role 'user'.
Second route periodically sends requests to restricted url with proper bearer token.

=== Camel routes

Both Camel routes are located in the `SampleCamelRouter` class. The first route exposes
restricted endpoint, accessible only for role 'user'. Second route starts from a timer,
that triggers periodically and creates a request authorized as user with role 'user'.
The first route puts into body message 'Hello ${principal}' and second route logs it.

=== Using Camel components

Apache Camel provides 200+ components which you can use to integrate and route messages between many systems
and data formats. To use any of these Camel components, add the component as a dependency to your project.

=== How to run

You can run this example using

    mvn spring-boot:run

=== To get info about the routes

To show a summary of all the routes

----
curl -XGET -s http://localhost:8080/camel/routes
----

To show detailed information for a specific route

----
curl -XGET -s http://localhost:8080/camel/routes/{id}/info
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
