= Camel Spring Boot Component Starters

Starters are Apache Camel modules intended to be used in Spring Boot applications. 
There is a `camel-xxx-starter` module for each Camel component which is supported on Spring Boot.

You should always use the `camel-xxx-starter` modules when using Spring Boot with Camel. These are the Camel components
which are officially supported with Spring Boot. If there is no `camel-xxx-starter` module then the Camel component is not supported on Spring Boot with Camel.

Starters are created to meet the following requirements:

* Allow the auto-configuration of the component through the native Spring Boot configuration system (compatible with IDE tooling)
* Manage transitive logging dependencies to better integrate with Spring Boot logging system
* Include additional dependencies and align transitive ones to minimize the effort of creating a working Spring Boot application
* May include additional features such as additonal configurations, actuators, or health checks

Each Camel starter has its own integration test (in path `tests/camel-itest-spring-boot`) that verifies its compatibility with the current release of Spring Boot.

