= Component Starters

Apache Camel Spring Boot supports the following Camel artifacts as Spring Boot Starters

== Camel Components

// components: START
Number of Camel components: 336 in 269 JAR artifacts (3 deprecated)

[width="100%",cols="4,1,5",options="header"]
|===
| Component | Since | Description

| link:https://camel.apache.org/components/latest/activemq-component.html[ActiveMQ] (camel-activemq-starter) +
`activemq:destinationType:destinationName` | 1.0 | Send messages to (or consume from) Apache ActiveMQ. This component extends the Camel JMS component.

| link:https://camel.apache.org/components/latest/amqp-component.html[AMQP] (camel-amqp-starter) +
`amqp:destinationType:destinationName` | 1.2 | Messaging with AMQP protocol using Apache QPid Client.

| link:https://camel.apache.org/components/latest/apns-component.html[APNS] (camel-apns-starter) +
`apns:name` | 2.8 | Send notifications to Apple iOS devices.

| link:https://camel.apache.org/components/latest/arangodb-component.html[ArangoDb] (camel-arangodb-starter) +
`arangodb:database` | 3.5.0-SNAPSHOT | Perform operations on ArangoDb documents, collections and graphs.

| link:https://camel.apache.org/components/latest/as2-component.html[AS2] (camel-as2-starter) +
`as2:apiName/methodName` | 2.22 | Transfer data securely and reliably using the AS2 protocol (RFC4130).

| link:https://camel.apache.org/components/latest/asterisk-component.html[Asterisk] (camel-asterisk-starter) +
`asterisk:name` | 2.18 | Interact with Asterisk PBX Server.

| link:https://camel.apache.org/components/latest/ahc-component.html[Async HTTP Client (AHC)] (camel-ahc-starter) +
`ahc:httpUri` | 2.8 | Call external HTTP services using Async Http Client.

| link:https://camel.apache.org/components/latest/ahc-ws-component.html[Async HTTP Client (AHC) Websocket] (camel-ahc-ws-starter) +
`ahc-ws:httpUri` | 2.14 | Exchange data with external Websocket servers using Async Http Client.

| link:https://camel.apache.org/components/latest/atmos-component.html[Atmos] (camel-atmos-starter) +
`atmos:name/operation` | 2.15 | Integract with EMC's ViPR object data services using the Atmos Client.

| link:https://camel.apache.org/components/latest/atmosphere-websocket-component.html[Atmosphere Websocket] (camel-atmosphere-websocket-starter) +
`atmosphere-websocket:servicePath` | 2.14 | Expose WebSocket endpoints using the Atmosphere framework.

| link:https://camel.apache.org/components/latest/atom-component.html[Atom] (camel-atom-starter) +
`atom:feedUri` | 1.2 | Poll Atom RSS feeds.

| link:https://camel.apache.org/components/latest/atomix-map-component.html[Atomix Map] (camel-atomix-starter) +
`atomix-map:resourceName` | 2.20 | Access Atomix's distributed map.

| link:https://camel.apache.org/components/latest/atomix-messaging-component.html[Atomix Messaging] (camel-atomix-starter) +
`atomix-messaging:resourceName` | 2.20 | Access Atomix's group messaging.

| link:https://camel.apache.org/components/latest/atomix-multimap-component.html[Atomix MultiMap] (camel-atomix-starter) +
`atomix-multimap:resourceName` | 2.20 | Access Atomix's distributed multi map.

| link:https://camel.apache.org/components/latest/atomix-queue-component.html[Atomix Queue] (camel-atomix-starter) +
`atomix-queue:resourceName` | 2.20 | Access Atomix's distributed queue.

| link:https://camel.apache.org/components/latest/atomix-set-component.html[Atomix Set] (camel-atomix-starter) +
`atomix-set:resourceName` | 2.20 | Access Atomix's distributed set.

| link:https://camel.apache.org/components/latest/atomix-value-component.html[Atomix Value] (camel-atomix-starter) +
`atomix-value:resourceName` | 2.20 | Access Atomix's distributed value.

| link:https://camel.apache.org/components/latest/avro-component.html[Avro RPC] (camel-avro-rpc-starter) +
`avro:transport:host:port/messageName` | 2.10 | Produce or consume Apache Avro RPC services.

| link:https://camel.apache.org/components/latest/aws2-athena-component.html[AWS 2 Athena] (camel-aws2-athena-starter) +
`aws2-athena:label` | 3.4 | Access AWS Athena service using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-cw-component.html[AWS 2 CloudWatch] (camel-aws2-cw-starter) +
`aws2-cw:namespace` | 3.1 | Sending metrics to AWS CloudWatch using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-ddb-component.html[AWS 2 DynamoDB] (camel-aws2-ddb-starter) +
`aws2-ddb:tableName` | 3.1 | Store and retrieve data from AWS DynamoDB service using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-ddbstream-component.html[AWS 2 DynamoDB Streams] (camel-aws2-ddb-starter) +
`aws2-ddbstream:tableName` | 3.1 | Receive messages from AWS DynamoDB Stream service using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-ec2-component.html[AWS 2 Elastic Compute Cloud (EC2)] (camel-aws2-ec2-starter) +
`aws2-ec2:label` | 3.1 | Manage AWS EC2 instances using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-ecs-component.html[AWS 2 Elastic Container Service (ECS)] (camel-aws2-ecs-starter) +
`aws2-ecs:label` | 3.1 | Manage AWS ECS cluster instances using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-eks-component.html[AWS 2 Elastic Kubernetes Service (EKS)] (camel-aws2-eks-starter) +
`aws2-eks:label` | 3.1 | Manage AWS EKS cluster instances using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-iam-component.html[AWS 2 Identity and Access Management (IAM)] (camel-aws2-iam-starter) +
`aws2-iam:label` | 3.1 | Manage AWS IAM instances using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-kms-component.html[AWS 2 Key Management Service (KMS)] (camel-aws2-kms-starter) +
`aws2-kms:label` | 3.1 | Manage keys stored in AWS KMS instances using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-kinesis-component.html[AWS 2 Kinesis] (camel-aws2-kinesis-starter) +
`aws2-kinesis:streamName` | 3.2 | Consume and produce records from and to AWS Kinesis Streams using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-kinesis-firehose-component.html[AWS 2 Kinesis Firehose] (camel-aws2-kinesis-starter) +
`aws2-kinesis-firehose:streamName` | 3.2 | Produce data to AWS Kinesis Firehose streams using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-lambda-component.html[AWS 2 Lambda] (camel-aws2-lambda-starter) +
`aws2-lambda:function` | 3.2 | Manage and invoke AWS Lambda functions using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-msk-component.html[AWS 2 Managed Streaming for Apache Kafka (MSK)] (camel-aws2-msk-starter) +
`aws2-msk:label` | 3.1 | Manage AWS MSK instances using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-mq-component.html[AWS 2 MQ] (camel-aws2-mq-starter) +
`aws2-mq:label` | 3.1 | Manage AWS MQ instances using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-s3-component.html[AWS 2 S3 Storage Service] (camel-aws2-s3-starter) +
`aws2-s3://bucketNameOrArn` | 3.2 | Store and retrieve objects from AWS S3 Storage Service using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-sts-component.html[AWS 2 Security Token Service (STS)] (camel-aws2-sts-starter) +
`aws2-sts:label` | 3.5 | Manage AWS ECS cluster instances using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-ses-component.html[AWS 2 Simple Email Service (SES)] (camel-aws2-ses-starter) +
`aws2-ses:from` | 3.1 | Send e-mails through AWS SES service using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-sns-component.html[AWS 2 Simple Notification System (SNS)] (camel-aws2-sns-starter) +
`aws2-sns:topicNameOrArn` | 3.1 | Send messages to an AWS Simple Notification Topic using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-sqs-component.html[AWS 2 Simple Queue Service (SQS)] (camel-aws2-sqs-starter) +
`aws2-sqs:queueNameOrArn` | 3.1 | Sending and receive messages to/from AWS SQS service using AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws2-translate-component.html[AWS 2 Translate] (camel-aws2-translate-starter) +
`aws2-translate:label` | 3.1 | Translate texts using AWS Translate and AWS SDK version 2.x.

| link:https://camel.apache.org/components/latest/aws-cw-component.html[AWS CloudWatch] (camel-aws-cw-starter) +
`aws-cw:namespace` | 2.11 | Send metrics to AWS CloudWatch.

| link:https://camel.apache.org/components/latest/aws-ddb-component.html[AWS DynamoDB] (camel-aws-ddb-starter) +
`aws-ddb:tableName` | 2.10 | Store and retrieve data from AWS DynamoDB service.

| link:https://camel.apache.org/components/latest/aws-ddbstream-component.html[AWS DynamoDB Streams] (camel-aws-ddb-starter) +
`aws-ddbstream:tableName` | 2.17 | Receive messages from AWS DynamoDB Stream service.

| link:https://camel.apache.org/components/latest/aws-ec2-component.html[AWS Elastic Compute Cloud (EC2)] (camel-aws-ec2-starter) +
`aws-ec2:label` | 2.16 | Manage AWS EC2 instances.

| link:https://camel.apache.org/components/latest/aws-ecs-component.html[AWS Elastic Container Service (ECS)] (camel-aws-ecs-starter) +
`aws-ecs:label` | 3.0 | Manage AWS ECS cluster instances.

| link:https://camel.apache.org/components/latest/aws-eks-component.html[AWS Elastic Kubernetes Service (EKS)] (camel-aws-eks-starter) +
`aws-eks:label` | 3.0 | Manage AWS EKS cluster instances.

| link:https://camel.apache.org/components/latest/aws-iam-component.html[AWS Identity and Access Management (IAM)] (camel-aws-iam-starter) +
`aws-iam:label` | 2.23 | Manage AWS IAM instances.

| link:https://camel.apache.org/components/latest/aws-kms-component.html[AWS Key Management Service (KMS)] (camel-aws-kms-starter) +
`aws-kms:label` | 2.21 | Manage keys stored in AWS KMS instances.

| link:https://camel.apache.org/components/latest/aws-kinesis-component.html[AWS Kinesis] (camel-aws-kinesis-starter) +
`aws-kinesis:streamName` | 2.17 | Consume and produce records from AWS Kinesis Streams.

| link:https://camel.apache.org/components/latest/aws-kinesis-firehose-component.html[AWS Kinesis Firehose] (camel-aws-kinesis-starter) +
`aws-kinesis-firehose:streamName` | 2.19 | Consume data from AWS Kinesis Firehose streams.

| link:https://camel.apache.org/components/latest/aws-lambda-component.html[AWS Lambda] (camel-aws-lambda-starter) +
`aws-lambda:function` | 2.20 | Manage and invoke AWS Lambda functions.

| link:https://camel.apache.org/components/latest/aws-msk-component.html[AWS Managed Streaming for Apache Kafka (MSK)] (camel-aws-msk-starter) +
`aws-msk:label` | 3.0 | Manage AWS MSK instances.

| link:https://camel.apache.org/components/latest/aws-mq-component.html[AWS MQ] (camel-aws-mq-starter) +
`aws-mq:label` | 2.21 | Manage AWS MQ instances.

| link:https://camel.apache.org/components/latest/aws-s3-component.html[AWS S3 Storage Service] (camel-aws-s3-starter) +
`aws-s3://bucketNameOrArn` | 2.8 | Store and retrieve objects from AWS S3 Storage Service.

| link:https://camel.apache.org/components/latest/aws-ses-component.html[AWS Simple Email Service (SES)] (camel-aws-ses-starter) +
`aws-ses:from` | 2.9 | Send e-mails through AWS SES service.

| link:https://camel.apache.org/components/latest/aws-sns-component.html[AWS Simple Notification System (SNS)] (camel-aws-sns-starter) +
`aws-sns:topicNameOrArn` | 2.8 | Send messages to an AWS Simple Notification Topic.

| link:https://camel.apache.org/components/latest/aws-sqs-component.html[AWS Simple Queue Service (SQS)] (camel-aws-sqs-starter) +
`aws-sqs:queueNameOrArn` | 2.6 | Sending and receive messages to/from AWS SQS service.

| link:https://camel.apache.org/components/latest/aws-swf-component.html[AWS Simple Workflow (SWF)] (camel-aws-swf-starter) +
`aws-swf:type` | 2.13 | Manage workflows in the AWS Simple Workflow service.

| link:https://camel.apache.org/components/latest/aws-sdb-component.html[AWS SimpleDB] (camel-aws-sdb-starter) +
`aws-sdb:domainName` | 2.9 | Store and Retrieve data from/to AWS SDB service.

| link:https://camel.apache.org/components/latest/aws-translate-component.html[AWS Translate] (camel-aws-translate-starter) +
`aws-translate:label` | 3.0 | Translate texts using AWS Translate.

| link:https://camel.apache.org/components/latest/azure-storage-blob-component.html[Azure Storage Blob Service] (camel-azure-storage-blob-starter) +
`azure-storage-blob:containerName` | 3.3 | Store and retrieve blobs from Azure Storage Blob Service using SDK v12.

| link:https://camel.apache.org/components/latest/azure-blob-component.html[Azure Storage Blob Service (Deprecated)] (camel-azure-starter) +
`azure-blob:containerOrBlobUri` | 2.19 | *deprecated* Store and retrieve blobs from Azure Storage Blob Service.

| link:https://camel.apache.org/components/latest/azure-storage-queue-component.html[Azure Storage Queue Service] (camel-azure-storage-queue-starter) +
`azure-storage-queue:queueName` | 3.3 | The azure-storage-queue component is used for storing and retrieving the messages to/from Azure Storage Queue using Azure SDK v12.

| link:https://camel.apache.org/components/latest/azure-queue-component.html[Azure Storage Queue Service (Deprecated)] (camel-azure-starter) +
`azure-queue:containerAndQueueUri` | 2.19 | *deprecated* Store and retrieve messages from Azure Storage Queue Service.

| link:https://camel.apache.org/components/latest/bean-component.html[Bean] (camel-bean-starter) +
`bean:beanName` | 1.0 | Invoke methods of Java beans stored in Camel registry.

| link:https://camel.apache.org/components/latest/bean-validator-component.html[Bean Validator] (camel-bean-validator-starter) +
`bean-validator:label` | 2.3 | Validate the message body using the Java Bean Validation API.

| link:https://camel.apache.org/components/latest/beanstalk-component.html[Beanstalk] (camel-beanstalk-starter) +
`beanstalk:connectionSettings` | 2.15 | Retrieve and post-process Beanstalk jobs.

| link:https://camel.apache.org/components/latest/bonita-component.html[Bonita] (camel-bonita-starter) +
`bonita:operation` | 2.19 | Communicate with a remote Bonita BPM process engine.

| link:https://camel.apache.org/components/latest/box-component.html[Box] (camel-box-starter) +
`box:apiName/methodName` | 2.14 | Upload, download and manage files, folders, groups, collaborations, etc. on box.com.

| link:https://camel.apache.org/components/latest/braintree-component.html[Braintree] (camel-braintree-starter) +
`braintree:apiName/methodName` | 2.17 | Process payments using Braintree Payments.

| link:https://camel.apache.org/components/latest/browse-component.html[Browse] (camel-browse-starter) +
`browse:name` | 1.3 | Inspect the messages received on endpoints supporting BrowsableEndpoint.

| link:https://camel.apache.org/components/latest/caffeine-cache-component.html[Caffeine Cache] (camel-caffeine-starter) +
`caffeine-cache:cacheName` | 2.20 | Perform caching operations using Caffeine Cache.

| link:https://camel.apache.org/components/latest/caffeine-loadcache-component.html[Caffeine LoadCache] (camel-caffeine-starter) +
`caffeine-loadcache:cacheName` | 2.20 | Perform caching operations using Caffeine Cache with an attached CacheLoader.

| link:https://camel.apache.org/components/latest/cql-component.html[Cassandra CQL] (camel-cassandraql-starter) +
`cql:beanRef:hosts:port/keyspace` | 2.15 | Integrate with Cassandra 2.0 using the CQL3 API (not the Thrift API).

| link:https://camel.apache.org/components/latest/chatscript-component.html[ChatScript] (camel-chatscript-starter) +
`chatscript:host:port/botName` | 3.0 | Chat with a ChatScript Server.

| link:https://camel.apache.org/components/latest/chunk-component.html[Chunk] (camel-chunk-starter) +
`chunk:resourceUri` | 2.15 | Transform messages using Chunk templating engine.

| link:https://camel.apache.org/components/latest/class-component.html[Class] (camel-bean-starter) +
`class:beanName` | 2.4 | Invoke methods of Java beans specified by class name.

| link:https://camel.apache.org/components/latest/cm-sms-component.html[CM SMS Gateway] (camel-cm-sms-starter) +
`cm-sms:host` | 2.18 | Send SMS messages via CM SMS Gateway.

| link:https://camel.apache.org/components/latest/cmis-component.html[CMIS] (camel-cmis-starter) +
`cmis:cmsUrl` | 2.11 | Read and write data from to/from a CMIS compliant content repositories.

| link:https://camel.apache.org/components/latest/coap-component.html[CoAP] (camel-coap-starter) +
`coap:uri` | 2.16 | Send and receive messages to/from COAP capable devices.

| link:https://camel.apache.org/components/latest/cometd-component.html[CometD] (camel-cometd-starter) +
`cometd:host:port/channelName` | 2.0 | Offers publish/subscribe, peer-to-peer (via a server), and RPC style messaging using the CometD/Bayeux protocol.

| link:https://camel.apache.org/components/latest/consul-component.html[Consul] (camel-consul-starter) +
`consul:apiEndpoint` | 2.18 | Integrate with Consul service discovery and configuration store.

| link:https://camel.apache.org/components/latest/controlbus-component.html[Control Bus] (camel-controlbus-starter) +
`controlbus:command:language` | 2.11 | Manage and monitor Camel routes.

| link:https://camel.apache.org/components/latest/corda-component.html[Corda] (camel-corda-starter) +
`corda:node` | 2.23 | Perform operations against Corda blockchain platform using corda-rpc library.

| link:https://camel.apache.org/components/latest/couchbase-component.html[Couchbase] (camel-couchbase-starter) +
`couchbase:protocol:hostname:port` | 2.19 | Query Couchbase Views with a poll strategy and/or perform various operations against Couchbase databases.

| link:https://camel.apache.org/components/latest/couchdb-component.html[CouchDB] (camel-couchdb-starter) +
`couchdb:protocol:hostname:port/database` | 2.11 | Consume changesets for inserts, updates and deletes in a CouchDB database, as well as get, save, update and delete documents from a CouchDB database.

| link:https://camel.apache.org/components/latest/cron-component.html[Cron] (camel-cron-starter) +
`cron:name` | 3.1 | A generic interface for triggering events at times specified through the Unix cron syntax.

| link:https://camel.apache.org/components/latest/crypto-component.html[Crypto (JCE)] (camel-crypto-starter) +
`crypto:cryptoOperation:name` | 2.3 | Sign and verify exchanges using the Signature Service of the Java Cryptographic Extension (JCE).

| link:https://camel.apache.org/components/latest/crypto-cms-component.html[Crypto CMS] (camel-crypto-cms-starter) +
`crypto-cms:cryptoOperation:name` | 2.20 | *deprecated* Encrypt, decrypt, sign and verify data in CMS Enveloped Data format.

| link:https://camel.apache.org/components/latest/cxf-component.html[CXF] (camel-cxf-starter) +
`cxf:beanId:address` | 1.0 | Expose SOAP WebServices using Apache CXF or connect to external WebServices using CXF WS client.

| link:https://camel.apache.org/components/latest/cxfrs-component.html[CXF-RS] (camel-cxf-starter) +
`cxfrs:beanId:address` | 2.0 | Expose JAX-RS REST services using Apache CXF or connect to external REST services using CXF REST client.

| link:https://camel.apache.org/components/latest/dataformat-component.html[Data Format] (camel-dataformat-starter) +
`dataformat:name:operation` | 2.12 | Use a Camel Data Format as a regular Camel Component.

| link:https://camel.apache.org/components/latest/dataset-component.html[Dataset] (camel-dataset-starter) +
`dataset:name` | 1.3 | Provide data for load & soak testing of your Camel application.

| link:https://camel.apache.org/components/latest/dataset-test-component.html[DataSet Test] (camel-dataset-starter) +
`dataset-test:name` | 1.3 | Extends the mock component by pulling messages from another endpoint on startup to set the expected message bodies.

| link:https://camel.apache.org/components/latest/debezium-mongodb-component.html[Debezium MongoDB Connector] (camel-debezium-mongodb-starter) +
`debezium-mongodb:name` | 3.0 | Capture changes from a MongoDB database.

| link:https://camel.apache.org/components/latest/debezium-mysql-component.html[Debezium MySQL Connector] (camel-debezium-mysql-starter) +
`debezium-mysql:name` | 3.0 | Capture changes from a MySQL database.

| link:https://camel.apache.org/components/latest/debezium-postgres-component.html[Debezium PostgresSQL Connector] (camel-debezium-postgres-starter) +
`debezium-postgres:name` | 3.0 | Capture changes from a PostgresSQL database.

| link:https://camel.apache.org/components/latest/debezium-sqlserver-component.html[Debezium SQL Server Connector] (camel-debezium-sqlserver-starter) +
`debezium-sqlserver:name` | 3.0 | Capture changes from an SQL Server database.

| link:https://camel.apache.org/components/latest/djl-component.html[Deep Java Library] (camel-djl-starter) +
`djl:application` | 3.3 | Infer Deep Learning models from message exchanges data using Deep Java Library (DJL).

| link:https://camel.apache.org/components/latest/digitalocean-component.html[DigitalOcean] (camel-digitalocean-starter) +
`digitalocean:operation` | 2.19 | Manage Droplets and resources within the DigitalOcean cloud.

| link:https://camel.apache.org/components/latest/direct-component.html[Direct] (camel-direct-starter) +
`direct:name` | 1.0 | Call another endpoint from the same Camel Context synchronously.

| link:https://camel.apache.org/components/latest/direct-vm-component.html[Direct VM] (camel-directvm-starter) +
`direct-vm:name` | 2.10 | Call another endpoint from any Camel Context in the same JVM synchronously.

| link:https://camel.apache.org/components/latest/disruptor-component.html[Disruptor] (camel-disruptor-starter) +
`disruptor:name` | 2.12 | Provides asynchronous SEDA behavior using LMAX Disruptor.

| link:https://camel.apache.org/components/latest/dns-component.html[DNS] (camel-dns-starter) +
`dns:dnsType` | 2.7 | Perform DNS queries using DNSJava.

| link:https://camel.apache.org/components/latest/docker-component.html[Docker] (camel-docker-starter) +
`docker:operation` | 2.15 | Manage Docker containers.

| link:https://camel.apache.org/components/latest/dozer-component.html[Dozer] (camel-dozer-starter) +
`dozer:name` | 2.15 | Map between Java beans using the Dozer mapping library.

| link:https://camel.apache.org/components/latest/drill-component.html[Drill] (camel-drill-starter) +
`drill:host` | 2.19 | Perform queries against an Apache Drill cluster.

| link:https://camel.apache.org/components/latest/dropbox-component.html[Dropbox] (camel-dropbox-starter) +
`dropbox:operation` | 2.14 | Upload, download and manage files, folders, groups, collaborations, etc on Dropbox.

| link:https://camel.apache.org/components/latest/ehcache-component.html[Ehcache] (camel-ehcache-starter) +
`ehcache:cacheName` | 2.18 | Perform caching operations using Ehcache.

| link:https://camel.apache.org/components/latest/elasticsearch-rest-component.html[Elasticsearch Rest] (camel-elasticsearch-rest-starter) +
`elasticsearch-rest:clusterName` | 2.21 | Send requests to with an ElasticSearch via REST API.

| link:https://camel.apache.org/components/latest/elsql-component.html[ElSQL] (camel-elsql-starter) +
`elsql:elsqlName:resourceUri` | 2.16 | Use ElSql to define SQL queries. Extends the SQL Component.

| link:https://camel.apache.org/components/latest/etcd-keys-component.html[Etcd Keys] (camel-etcd-starter) +
`etcd-keys:path` | 2.18 | Get, set or delete keys in etcd key-value store.

| link:https://camel.apache.org/components/latest/etcd-stats-component.html[Etcd Stats] (camel-etcd-starter) +
`etcd-stats:path` | 2.18 | Access etcd cluster statistcs.

| link:https://camel.apache.org/components/latest/etcd-watch-component.html[Etcd Watch] (camel-etcd-starter) +
`etcd-watch:path` | 2.18 | Watch specific etcd keys or directories for changes.

| link:https://camel.apache.org/components/latest/exec-component.html[Exec] (camel-exec-starter) +
`exec:executable` | 2.3 | Execute commands on the underlying operating system.

| link:https://camel.apache.org/components/latest/facebook-component.html[Facebook] (camel-facebook-starter) +
`facebook:methodName` | 2.14 | Send requests to Facebook APIs supported by Facebook4J.

| link:https://camel.apache.org/components/latest/fhir-component.html[FHIR] (camel-fhir-starter) +
`fhir:apiName/methodName` | 2.23 | Exchange information in the healthcare domain using the FHIR (Fast Healthcare Interoperability Resources) standard.

| link:https://camel.apache.org/components/latest/file-component.html[File] (camel-file-starter) +
`file:directoryName` | 1.0 | Read and write files.

| link:https://camel.apache.org/components/latest/file-watch-component.html[File Watch] (camel-file-watch-starter) +
`file-watch:path` | 3.0 | Get notified about file events in a directory using java.nio.file.WatchService.

| link:https://camel.apache.org/components/latest/flatpack-component.html[Flatpack] (camel-flatpack-starter) +
`flatpack:type:resourceUri` | 1.4 | Parse fixed width and delimited files using the FlatPack library.

| link:https://camel.apache.org/components/latest/flink-component.html[Flink] (camel-flink-starter) +
`flink:endpointType` | 2.18 | Send DataSet jobs to an Apache Flink cluster.

| link:https://camel.apache.org/components/latest/fop-component.html[FOP] (camel-fop-starter) +
`fop:outputType` | 2.10 | Render messages into PDF and other output formats supported by Apache FOP.

| link:https://camel.apache.org/components/latest/freemarker-component.html[Freemarker] (camel-freemarker-starter) +
`freemarker:resourceUri` | 2.10 | Transform messages using FreeMarker templates.

| link:https://camel.apache.org/components/latest/ftp-component.html[FTP] (camel-ftp-starter) +
`ftp:host:port/directoryName` | 1.1 | Upload and download files to/from FTP servers.

| link:https://camel.apache.org/components/latest/ftps-component.html[FTPS] (camel-ftp-starter) +
`ftps:host:port/directoryName` | 2.2 | Upload and download files to/from FTP servers supporting the FTPS protocol.

| link:https://camel.apache.org/components/latest/ganglia-component.html[Ganglia] (camel-ganglia-starter) +
`ganglia:host:port` | 2.15 | Send metrics to Ganglia monitoring system.

| link:https://camel.apache.org/components/latest/geocoder-component.html[Geocoder] (camel-geocoder-starter) +
`geocoder:address:latlng` | 2.12 | Find geocodes (latitude and longitude) for a given address or the other way round.

| link:https://camel.apache.org/components/latest/git-component.html[Git] (camel-git-starter) +
`git:localPath` | 2.16 | Perform operations on git repositories.

| link:https://camel.apache.org/components/latest/github-component.html[GitHub] (camel-github-starter) +
`github:type/branchName` | 2.15 | Interact with the GitHub API.

| link:https://camel.apache.org/components/latest/google-bigquery-component.html[Google BigQuery] (camel-google-bigquery-starter) +
`google-bigquery:projectId:datasetId:tableId` | 2.20 | Google BigQuery data warehouse for analytics.

| link:https://camel.apache.org/components/latest/google-bigquery-sql-component.html[Google BigQuery Standard SQL] (camel-google-bigquery-starter) +
`google-bigquery-sql:projectId:query` | 2.23 | Access Google Cloud BigQuery service using SQL queries.

| link:https://camel.apache.org/components/latest/google-calendar-component.html[Google Calendar] (camel-google-calendar-starter) +
`google-calendar:apiName/methodName` | 2.15 | Perform various operations on a Google Calendar.

| link:https://camel.apache.org/components/latest/google-calendar-stream-component.html[Google Calendar Stream] (camel-google-calendar-starter) +
`google-calendar-stream:index` | 2.23 | Poll for changes in a Google Calendar.

| link:https://camel.apache.org/components/latest/google-drive-component.html[Google Drive] (camel-google-drive-starter) +
`google-drive:apiName/methodName` | 2.14 | Manage files in Google Drive.

| link:https://camel.apache.org/components/latest/google-mail-component.html[Google Mail] (camel-google-mail-starter) +
`google-mail:apiName/methodName` | 2.15 | Manage messages in Google Mail.

| link:https://camel.apache.org/components/latest/google-mail-stream-component.html[Google Mail Stream] (camel-google-mail-starter) +
`google-mail-stream:index` | 2.22 | Poll for incoming messages in Google Mail.

| link:https://camel.apache.org/components/latest/google-pubsub-component.html[Google Pubsub] (camel-google-pubsub-starter) +
`google-pubsub:projectId:destinationName` | 2.19 | Send and receive messages to/from Google Cloud Platform PubSub Service.

| link:https://camel.apache.org/components/latest/google-sheets-component.html[Google Sheets] (camel-google-sheets-starter) +
`google-sheets:apiName/methodName` | 2.23 | Manage spreadsheets in Google Sheets.

| link:https://camel.apache.org/components/latest/google-sheets-stream-component.html[Google Sheets Stream] (camel-google-sheets-starter) +
`google-sheets-stream:apiName` | 2.23 | Poll for changes in Google Sheets.

| link:https://camel.apache.org/components/latest/gora-component.html[Gora] (camel-gora-starter) +
`gora:name` | 2.14 | Access NoSQL databases using the Apache Gora framework.

| link:https://camel.apache.org/components/latest/graphql-component.html[GraphQL] (camel-graphql-starter) +
`graphql:httpUri` | 3.0 | Send GraphQL queries and mutations to external systems.

| link:https://camel.apache.org/components/latest/grpc-component.html[gRPC] (camel-grpc-starter) +
`grpc:host:port/service` | 2.19 | Expose gRPC endpoints and access external gRPC endpoints.

| link:https://camel.apache.org/components/latest/guava-eventbus-component.html[Guava EventBus] (camel-guava-eventbus-starter) +
`guava-eventbus:eventBusRef` | 2.10 | Send and receive messages to/from Guava EventBus.

| link:https://camel.apache.org/components/latest/hazelcast-atomicvalue-component.html[Hazelcast Atomic Number] (camel-hazelcast-starter) +
`hazelcast-atomicvalue:cacheName` | 2.7 | Increment, decrement, set, etc. Hazelcast atomic number (a grid wide number).

| link:https://camel.apache.org/components/latest/hazelcast-instance-component.html[Hazelcast Instance] (camel-hazelcast-starter) +
`hazelcast-instance:cacheName` | 2.7 | Consume join/leave events of a cache instance in a Hazelcast cluster.

| link:https://camel.apache.org/components/latest/hazelcast-list-component.html[Hazelcast List] (camel-hazelcast-starter) +
`hazelcast-list:cacheName` | 2.7 | Perform operations on Hazelcast distributed list.

| link:https://camel.apache.org/components/latest/hazelcast-map-component.html[Hazelcast Map] (camel-hazelcast-starter) +
`hazelcast-map:cacheName` | 2.7 | Perform operations on Hazelcast distributed map.

| link:https://camel.apache.org/components/latest/hazelcast-multimap-component.html[Hazelcast Multimap] (camel-hazelcast-starter) +
`hazelcast-multimap:cacheName` | 2.7 | Perform operations on Hazelcast distributed multimap.

| link:https://camel.apache.org/components/latest/hazelcast-queue-component.html[Hazelcast Queue] (camel-hazelcast-starter) +
`hazelcast-queue:cacheName` | 2.7 | Perform operations on Hazelcast distributed queue.

| link:https://camel.apache.org/components/latest/hazelcast-replicatedmap-component.html[Hazelcast Replicated Map] (camel-hazelcast-starter) +
`hazelcast-replicatedmap:cacheName` | 2.16 | Perform operations on Hazelcast replicated map.

| link:https://camel.apache.org/components/latest/hazelcast-ringbuffer-component.html[Hazelcast Ringbuffer] (camel-hazelcast-starter) +
`hazelcast-ringbuffer:cacheName` | 2.16 | Perform operations on Hazelcast distributed ringbuffer.

| link:https://camel.apache.org/components/latest/hazelcast-seda-component.html[Hazelcast SEDA] (camel-hazelcast-starter) +
`hazelcast-seda:cacheName` | 2.7 | Asynchronously send/receive Exchanges between Camel routes running on potentially distinct JVMs/hosts backed by Hazelcast BlockingQueue.

| link:https://camel.apache.org/components/latest/hazelcast-set-component.html[Hazelcast Set] (camel-hazelcast-starter) +
`hazelcast-set:cacheName` | 2.7 | Perform operations on Hazelcast distributed set.

| link:https://camel.apache.org/components/latest/hazelcast-topic-component.html[Hazelcast Topic] (camel-hazelcast-starter) +
`hazelcast-topic:cacheName` | 2.15 | Send and receive messages to/from Hazelcast distributed topic.

| link:https://camel.apache.org/components/latest/hbase-component.html[HBase] (camel-hbase-starter) +
`hbase:tableName` | 2.10 | Reading and write from/to an HBase store (Hadoop database).

| link:https://camel.apache.org/components/latest/hdfs-component.html[HDFS] (camel-hdfs-starter) +
`hdfs:hostName:port/path` | 2.14 | Read and write from/to an HDFS filesystem using Hadoop 2.x.

| link:https://camel.apache.org/components/latest/hipchat-component.html[Hipchat] (camel-hipchat-starter) +
`hipchat:protocol:host:port` | 2.15 | Send and receive messages to/from Hipchat service.

| link:https://camel.apache.org/components/latest/http-component.html[HTTP] (camel-http-starter) +
`http:httpUri` | 2.3 | Send requests to external HTTP servers using Apache HTTP Client 4.x.

| link:https://camel.apache.org/components/latest/iec60870-client-component.html[IEC 60870 Client] (camel-iec60870-starter) +
`iec60870-client:uriPath` | 2.20 | IEC 60870 supervisory control and data acquisition (SCADA) client using NeoSCADA implementation.

| link:https://camel.apache.org/components/latest/iec60870-server-component.html[IEC 60870 Server] (camel-iec60870-starter) +
`iec60870-server:uriPath` | 2.20 | IEC 60870 supervisory control and data acquisition (SCADA) server using NeoSCADA implementation.

| link:https://camel.apache.org/components/latest/ignite-cache-component.html[Ignite Cache] (camel-ignite-starter) +
`ignite-cache:cacheName` | 2.17 | Perform cache operations on an Ignite cache or consume changes from a continuous query.

| link:https://camel.apache.org/components/latest/ignite-compute-component.html[Ignite Compute] (camel-ignite-starter) +
`ignite-compute:endpointId` | 2.17 | Run compute operations on an Ignite cluster.

| link:https://camel.apache.org/components/latest/ignite-events-component.html[Ignite Events] (camel-ignite-starter) +
`ignite-events:endpointId` | 2.17 | Receive events from an Ignite cluster by creating a local event listener.

| link:https://camel.apache.org/components/latest/ignite-idgen-component.html[Ignite ID Generator] (camel-ignite-starter) +
`ignite-idgen:name` | 2.17 | Interact with Ignite Atomic Sequences and ID Generators .

| link:https://camel.apache.org/components/latest/ignite-messaging-component.html[Ignite Messaging] (camel-ignite-starter) +
`ignite-messaging:topic` | 2.17 | Send and receive messages from an Ignite topic.

| link:https://camel.apache.org/components/latest/ignite-queue-component.html[Ignite Queues] (camel-ignite-starter) +
`ignite-queue:name` | 2.17 | Interact with Ignite Queue data structures.

| link:https://camel.apache.org/components/latest/ignite-set-component.html[Ignite Sets] (camel-ignite-starter) +
`ignite-set:name` | 2.17 | Interact with Ignite Set data structures.

| link:https://camel.apache.org/components/latest/infinispan-component.html[Infinispan] (camel-infinispan-starter) +
`infinispan:cacheName` | 2.13 | Read and write from/to Infinispan distributed key/value store and data grid.

| link:https://camel.apache.org/components/latest/influxdb-component.html[InfluxDB] (camel-influxdb-starter) +
`influxdb:connectionBean` | 2.18 | Interact with InfluxDB, a time series database.

| link:https://camel.apache.org/components/latest/iota-component.html[IOTA] (camel-iota-starter) +
`iota:name` | 2.23 | Manage financial transactions using IOTA distributed ledger.

| link:https://camel.apache.org/components/latest/ipfs-component.html[IPFS] (camel-ipfs-starter) +
`ipfs:ipfsCmd` | 2.23 | Access the Interplanetary File System (IPFS).

| link:https://camel.apache.org/components/latest/irc-component.html[IRC] (camel-irc-starter) +
`irc:hostname:port` | 1.1 | Send and receive messages to/from and IRC chat.

| link:https://camel.apache.org/components/latest/ironmq-component.html[IronMQ] (camel-ironmq-starter) +
`ironmq:queueName` | 2.17 | Send and receive messages to/from IronMQ an elastic and durable hosted message queue as a service.

| link:https://camel.apache.org/components/latest/websocket-jsr356-component.html[Javax Websocket] (camel-websocket-jsr356-starter) +
`websocket-jsr356:uri` | 2.23 | Expose websocket endpoints using JSR356.

| link:https://camel.apache.org/components/latest/jbpm-component.html[JBPM] (camel-jbpm-starter) +
`jbpm:connectionURL` | 2.6 | Interact with jBPM workflow engine over REST.

| link:https://camel.apache.org/components/latest/jcache-component.html[JCache] (camel-jcache-starter) +
`jcache:cacheName` | 2.17 | Perform caching operations against JSR107/JCache.

| link:https://camel.apache.org/components/latest/jclouds-component.html[JClouds] (camel-jclouds-starter) +
`jclouds:command:providerId` | 2.9 | Interact with jclouds compute & blobstore service.

| link:https://camel.apache.org/components/latest/jcr-component.html[JCR] (camel-jcr-starter) +
`jcr:host/base` | 1.3 | Read and write nodes to/from a JCR compliant content repository.

| link:https://camel.apache.org/components/latest/jdbc-component.html[JDBC] (camel-jdbc-starter) +
`jdbc:dataSourceName` | 1.2 | Access databases through SQL and JDBC.

| link:https://camel.apache.org/components/latest/jetty-component.html[Jetty] (camel-jetty-starter) +
`jetty:httpUri` | 1.2 | Expose HTTP endpoints using Jetty 9.

| link:https://camel.apache.org/components/latest/websocket-component.html[Jetty Websocket] (camel-websocket-starter) +
`websocket:host:port/resourceUri` | 2.10 | Expose websocket endpoints using Jetty.

| link:https://camel.apache.org/components/latest/jgroups-component.html[JGroups] (camel-jgroups-starter) +
`jgroups:clusterName` | 2.13 | Exchange messages with JGroups clusters.

| link:https://camel.apache.org/components/latest/jgroups-raft-component.html[JGroups raft] (camel-jgroups-raft-starter) +
`jgroups-raft:clusterName` | 2.24 | Exchange messages with JGroups-raft clusters.

| link:https://camel.apache.org/components/latest/jing-component.html[Jing] (camel-jing-starter) +
`jing:resourceUri` | 1.1 | Validate XML against a RelaxNG schema (XML Syntax or Compact Syntax) using Jing library.

| link:https://camel.apache.org/components/latest/jira-component.html[Jira] (camel-jira-starter) +
`jira:type` | 3.0 | Interact with JIRA issue tracker.

| link:https://camel.apache.org/components/latest/jms-component.html[JMS] (camel-jms-starter) +
`jms:destinationType:destinationName` | 1.0 | Sent and receive messages to/from a JMS Queue or Topic.

| link:https://camel.apache.org/components/latest/jmx-component.html[JMX] (camel-jmx-starter) +
`jmx:serverURL` | 2.6 | Receive JMX notifications.

| link:https://camel.apache.org/components/latest/jolt-component.html[JOLT] (camel-jolt-starter) +
`jolt:resourceUri` | 2.16 | JSON to JSON transformation using JOLT.

| link:https://camel.apache.org/components/latest/jooq-component.html[JOOQ] (camel-jooq-starter) +
`jooq:entityType` | 3.0 | Store and retrieve Java objects from an SQL database using JOOQ.

| link:https://camel.apache.org/components/latest/jpa-component.html[JPA] (camel-jpa-starter) +
`jpa:entityType` | 1.0 | Store and retrieve Java objects from databases using Java Persistence API (JPA).

| link:https://camel.apache.org/components/latest/jslt-component.html[JSLT] (camel-jslt-starter) +
`jslt:resourceUri` | 3.1 | Query or transform JSON payloads using an JSLT.

| link:https://camel.apache.org/components/latest/json-validator-component.html[JSON Schema Validator] (camel-json-validator-starter) +
`json-validator:resourceUri` | 2.20 | Validate JSON payloads using NetworkNT JSON Schema.

| link:https://camel.apache.org/components/latest/jsonata-component.html[JSONATA] (camel-jsonata-starter) +
`jsonata:resourceUri` | 3.5 | JSON to JSON transformation using JSONATA.

| link:https://camel.apache.org/components/latest/jt400-component.html[JT400] (camel-jt400-starter) +
`jt400:userID:password/systemName/objectPath.type` | 1.5 | Exchanges messages with an IBM i system using data queues, message queues, or program call. IBM i is the replacement for AS/400 and iSeries servers.

| link:https://camel.apache.org/components/latest/kafka-component.html[Kafka] (camel-kafka-starter) +
`kafka:topic` | 2.13 | Sent and receive messages to/from an Apache Kafka broker.

| link:https://camel.apache.org/components/latest/kubernetes-config-maps-component.html[Kubernetes ConfigMap] (camel-kubernetes-starter) +
`kubernetes-config-maps:masterUrl` | 2.17 | Perform operations on Kubernetes ConfigMaps and get notified on ConfigMaps changes.

| link:https://camel.apache.org/components/latest/kubernetes-deployments-component.html[Kubernetes Deployments] (camel-kubernetes-starter) +
`kubernetes-deployments:masterUrl` | 2.20 | Perform operations on Kubernetes Deployments and get notified on Deployment changes.

| link:https://camel.apache.org/components/latest/kubernetes-hpa-component.html[Kubernetes HPA] (camel-kubernetes-starter) +
`kubernetes-hpa:masterUrl` | 2.23 | Perform operations on Kubernetes Horizontal Pod Autoscalers (HPA) and get notified on HPA changes.

| link:https://camel.apache.org/components/latest/kubernetes-job-component.html[Kubernetes Job] (camel-kubernetes-starter) +
`kubernetes-job:masterUrl` | 2.23 | Perform operations on Kubernetes Jobs.

| link:https://camel.apache.org/components/latest/kubernetes-namespaces-component.html[Kubernetes Namespaces] (camel-kubernetes-starter) +
`kubernetes-namespaces:masterUrl` | 2.17 | Perform operations on Kubernetes Namespaces and get notified on Namespace changes.

| link:https://camel.apache.org/components/latest/kubernetes-nodes-component.html[Kubernetes Nodes] (camel-kubernetes-starter) +
`kubernetes-nodes:masterUrl` | 2.17 | Perform operations on Kubernetes Nodes and get notified on Node changes.

| link:https://camel.apache.org/components/latest/kubernetes-persistent-volumes-component.html[Kubernetes Persistent Volume] (camel-kubernetes-starter) +
`kubernetes-persistent-volumes:masterUrl` | 2.17 | Perform operations on Kubernetes Persistent Volumes and get notified on Persistent Volume changes.

| link:https://camel.apache.org/components/latest/kubernetes-persistent-volumes-claims-component.html[Kubernetes Persistent Volume Claim] (camel-kubernetes-starter) +
`kubernetes-persistent-volumes-claims:masterUrl` | 2.17 | Perform operations on Kubernetes Persistent Volumes Claims and get notified on Persistent Volumes Claim changes.

| link:https://camel.apache.org/components/latest/kubernetes-pods-component.html[Kubernetes Pods] (camel-kubernetes-starter) +
`kubernetes-pods:masterUrl` | 2.17 | Perform operations on Kubernetes Pods and get notified on Pod changes.

| link:https://camel.apache.org/components/latest/kubernetes-replication-controllers-component.html[Kubernetes Replication Controller] (camel-kubernetes-starter) +
`kubernetes-replication-controllers:masterUrl` | 2.17 | Perform operations on Kubernetes Replication Controllers and get notified on Replication Controllers changes.

| link:https://camel.apache.org/components/latest/kubernetes-resources-quota-component.html[Kubernetes Resources Quota] (camel-kubernetes-starter) +
`kubernetes-resources-quota:masterUrl` | 2.17 | Perform operations on Kubernetes Resources Quotas.

| link:https://camel.apache.org/components/latest/kubernetes-secrets-component.html[Kubernetes Secrets] (camel-kubernetes-starter) +
`kubernetes-secrets:masterUrl` | 2.17 | Perform operations on Kubernetes Secrets.

| link:https://camel.apache.org/components/latest/kubernetes-service-accounts-component.html[Kubernetes Service Account] (camel-kubernetes-starter) +
`kubernetes-service-accounts:masterUrl` | 2.17 | Perform operations on Kubernetes Service Accounts.

| link:https://camel.apache.org/components/latest/kubernetes-services-component.html[Kubernetes Services] (camel-kubernetes-starter) +
`kubernetes-services:masterUrl` | 2.17 | Perform operations on Kubernetes Services and get notified on Service changes.

| link:https://camel.apache.org/components/latest/kudu-component.html[Kudu] (camel-kudu-starter) +
`kudu:host:port/tableName` | 3.0 | Interact with Apache Kudu, a free and open source column-oriented data store of the Apache Hadoop ecosystem.

| link:https://camel.apache.org/components/latest/language-component.html[Language] (camel-language-starter) +
`language:languageName:resourceUri` | 2.5 | Execute scripts in any of the languages supported by Camel.

| link:https://camel.apache.org/components/latest/ldap-component.html[LDAP] (camel-ldap-starter) +
`ldap:dirContextName` | 1.5 | Perform searches on LDAP servers.

| link:https://camel.apache.org/components/latest/ldif-component.html[LDIF] (camel-ldif-starter) +
`ldif:ldapConnectionName` | 2.20 | Perform updates on an LDAP server from an LDIF body content.

| link:https://camel.apache.org/components/latest/log-component.html[Log] (camel-log-starter) +
`log:loggerName` | 1.1 | Log messages to the underlying logging mechanism.

| link:https://camel.apache.org/components/latest/lucene-component.html[Lucene] (camel-lucene-starter) +
`lucene:host:operation` | 2.2 | Perform inserts or queries against Apache Lucene databases.

| link:https://camel.apache.org/components/latest/lumberjack-component.html[Lumberjack] (camel-lumberjack-starter) +
`lumberjack:host:port` | 2.18 | Receive logs messages using the Lumberjack protocol.

| link:https://camel.apache.org/components/latest/mail-component.html[Mail] (camel-mail-starter) +
`imap:host:port` | 1.0 | Send and receive emails using imap, pop3 and smtp protocols.

| link:https://camel.apache.org/components/latest/master-component.html[Master] (camel-master-starter) +
`master:namespace:delegateUri` | 2.20 | Have only a single consumer in a cluster consuming from a given endpoint; with automatic failover if the JVM dies.

| link:https://camel.apache.org/components/latest/metrics-component.html[Metrics] (camel-metrics-starter) +
`metrics:metricsType:metricsName` | 2.14 | Collect various metrics directly from Camel routes using the DropWizard metrics library.

| link:https://camel.apache.org/components/latest/micrometer-component.html[Micrometer] (camel-micrometer-starter) +
`micrometer:metricsType:metricsName` | 2.22 | Collect various metrics directly from Camel routes using the Micrometer library.

| link:https://camel.apache.org/components/latest/mina-component.html[Mina] (camel-mina-starter) +
`mina:protocol:host:port` | 2.10 | Socket level networking using TCP or UDP with Apache Mina 2.x.

| link:https://camel.apache.org/components/latest/mllp-component.html[MLLP] (camel-mllp-starter) +
`mllp:hostname:port` | 2.17 | Communicate with external systems using the MLLP protocol.

| link:https://camel.apache.org/components/latest/mock-component.html[Mock] (camel-mock-starter) +
`mock:name` | 1.0 | Test routes and mediation rules using mocks.

| link:https://camel.apache.org/components/latest/mongodb-component.html[MongoDB] (camel-mongodb-starter) +
`mongodb:connectionBean` | 2.19 | Perform operations on MongoDB documents and collections.

| link:https://camel.apache.org/components/latest/mongodb-gridfs-component.html[MongoDB GridFS] (camel-mongodb-gridfs-starter) +
`mongodb-gridfs:connectionBean` | 2.18 | Interact with MongoDB GridFS.

| link:https://camel.apache.org/components/latest/msv-component.html[MSV] (camel-msv-starter) +
`msv:resourceUri` | 1.1 | Validate XML payloads using Multi-Schema Validator (MSV).

| link:https://camel.apache.org/components/latest/mustache-component.html[Mustache] (camel-mustache-starter) +
`mustache:resourceUri` | 2.12 | Transform messages using a Mustache template.

| link:https://camel.apache.org/components/latest/mvel-component.html[MVEL] (camel-mvel-starter) +
`mvel:resourceUri` | 2.12 | Transform messages using an MVEL template.

| link:https://camel.apache.org/components/latest/mybatis-component.html[MyBatis] (camel-mybatis-starter) +
`mybatis:statement` | 2.7 | Performs a query, poll, insert, update or delete in a relational database using MyBatis.

| link:https://camel.apache.org/components/latest/mybatis-bean-component.html[MyBatis Bean] (camel-mybatis-starter) +
`mybatis-bean:beanName:methodName` | 2.22 | Perform queries, inserts, updates or deletes in a relational database using MyBatis.

| link:https://camel.apache.org/components/latest/nagios-component.html[Nagios] (camel-nagios-starter) +
`nagios:host:port` | 2.3 | Send passive checks to Nagios using JSendNSCA.

| link:https://camel.apache.org/components/latest/nats-component.html[Nats] (camel-nats-starter) +
`nats:topic` | 2.17 | Send and receive messages from NATS messaging system.

| link:https://camel.apache.org/components/latest/netty-component.html[Netty] (camel-netty-starter) +
`netty:protocol:host:port` | 2.14 | Socket level networking using TCP or UDP with the Netty 4.x.

| link:https://camel.apache.org/components/latest/netty-http-component.html[Netty HTTP] (camel-netty-http-starter) +
`netty-http:protocol:host:port/path` | 2.14 | Netty HTTP server and client using the Netty 4.x.

| link:https://camel.apache.org/components/latest/nitrite-component.html[Nitrite] (camel-nitrite-starter) +
`nitrite:database` | 3.0 | Access Nitrite databases.

| link:https://camel.apache.org/components/latest/nsq-component.html[NSQ] (camel-nsq-starter) +
`nsq:topic` | 2.23 | Send and receive messages from NSQ realtime distributed messaging platform.

| link:https://camel.apache.org/components/latest/olingo2-component.html[Olingo2] (camel-olingo2-starter) +
`olingo2:apiName/methodName` | 2.14 | Communicate with OData 2.0 services using Apache Olingo.

| link:https://camel.apache.org/components/latest/olingo4-component.html[Olingo4] (camel-olingo4-starter) +
`olingo4:apiName/methodName` | 2.19 | Communicate with OData 4.0 services using Apache Olingo OData API.

| link:https://camel.apache.org/components/latest/milo-client-component.html[OPC UA Client] (camel-milo-starter) +
`milo-client:endpointUri` | 2.19 | Connect to OPC UA servers using the binary protocol for acquiring telemetry data.

| link:https://camel.apache.org/components/latest/milo-server-component.html[OPC UA Server] (camel-milo-starter) +
`milo-server:itemId` | 2.19 | Make telemetry data available as an OPC UA server.

| link:https://camel.apache.org/components/latest/openshift-build-configs-component.html[Openshift Build Config] (camel-kubernetes-starter) +
`openshift-build-configs:masterUrl` | 2.17 | Perform operations on OpenShift Build Configs.

| link:https://camel.apache.org/components/latest/openshift-builds-component.html[Openshift Builds] (camel-kubernetes-starter) +
`openshift-builds:masterUrl` | 2.17 | Perform operations on OpenShift Builds.

| link:https://camel.apache.org/components/latest/openstack-cinder-component.html[OpenStack Cinder] (camel-openstack-starter) +
`openstack-cinder:host` | 2.19 | Access data in OpenStack Cinder block storage.

| link:https://camel.apache.org/components/latest/openstack-glance-component.html[OpenStack Glance] (camel-openstack-starter) +
`openstack-glance:host` | 2.19 | Manage VM images and metadata definitions in OpenStack Glance.

| link:https://camel.apache.org/components/latest/openstack-keystone-component.html[OpenStack Keystone] (camel-openstack-starter) +
`openstack-keystone:host` | 2.19 | Access OpenStack Keystone for API client authentication, service discovery and distributed multi-tenant authorization.

| link:https://camel.apache.org/components/latest/openstack-neutron-component.html[OpenStack Neutron] (camel-openstack-starter) +
`openstack-neutron:host` | 2.19 | Access OpenStack Neutron for network services.

| link:https://camel.apache.org/components/latest/openstack-nova-component.html[OpenStack Nova] (camel-openstack-starter) +
`openstack-nova:host` | 2.19 | Access OpenStack to manage compute resources.

| link:https://camel.apache.org/components/latest/openstack-swift-component.html[OpenStack Swift] (camel-openstack-starter) +
`openstack-swift:host` | 2.19 | Access OpenStack Swift object/blob store.

| link:https://camel.apache.org/components/latest/optaplanner-component.html[OptaPlanner] (camel-optaplanner-starter) +
`optaplanner:configFile` | 2.13 | Solve planning problems with OptaPlanner.

| link:https://camel.apache.org/components/latest/paho-component.html[Paho] (camel-paho-starter) +
`paho:topic` | 2.16 | Communicate with MQTT message brokers using Eclipse Paho MQTT Client.

| link:https://camel.apache.org/components/latest/pdf-component.html[PDF] (camel-pdf-starter) +
`pdf:operation` | 2.16 | Create, modify or extract content from PDF documents.

| link:https://camel.apache.org/components/latest/platform-http-component.html[Platform HTTP] (camel-platform-http-starter) +
`platform-http:path` | 3.0 | Expose HTTP endpoints using the HTTP server available in the current platform.

| link:https://camel.apache.org/components/latest/pgevent-component.html[PostgresSQL Event] (camel-pgevent-starter) +
`pgevent:host:port/database/channel` | 2.15 | Send and receive PostgreSQL events via LISTEN and NOTIFY commands.

| link:https://camel.apache.org/components/latest/pg-replication-slot-component.html[PostgresSQL Replication Slot] (camel-pg-replication-slot-starter) +
`pg-replication-slot:host:port/database/slot:outputPlugin` | 3.0 | Poll for PostgreSQL Write-Ahead Log (WAL) records using Streaming Replication Slots.

| link:https://camel.apache.org/components/latest/lpr-component.html[Printer] (camel-printer-starter) +
`lpr:hostname:port/printername` | 2.1 | Send print jobs to printers.

| link:https://camel.apache.org/components/latest/pubnub-component.html[PubNub] (camel-pubnub-starter) +
`pubnub:channel` | 2.19 | Send and receive messages to/from PubNub data stream network for connected devices.

| link:https://camel.apache.org/components/latest/pulsar-component.html[Pulsar] (camel-pulsar-starter) +
`pulsar:persistence://tenant/namespace/topic` | 2.24 | Send and receive messages from/to Apache Pulsar messaging system.

| link:https://camel.apache.org/components/latest/quartz-component.html[Quartz] (camel-quartz-starter) +
`quartz:groupName/triggerName` | 2.12 | Schedule sending of messages using the Quartz 2.x scheduler.

| link:https://camel.apache.org/components/latest/quickfix-component.html[QuickFix] (camel-quickfix-starter) +
`quickfix:configurationName` | 2.1 | Open a Financial Interchange (FIX) session using an embedded QuickFix/J engine.

| link:https://camel.apache.org/components/latest/rabbitmq-component.html[RabbitMQ] (camel-rabbitmq-starter) +
`rabbitmq:exchangeName` | 2.12 | Send and receive messages from RabbitMQ instances.

| link:https://camel.apache.org/components/latest/reactive-streams-component.html[Reactive Streams] (camel-reactive-streams-starter) +
`reactive-streams:stream` | 2.19 | Exchange messages with reactive stream processing libraries compatible with the reactive streams standard.

| link:https://camel.apache.org/components/latest/ref-component.html[Ref] (camel-ref-starter) +
`ref:name` | 1.2 | Route messages to an endpoint looked up dynamically by name in the Camel Registry.

| link:https://camel.apache.org/components/latest/rest-component.html[REST] (camel-rest-starter) +
`rest:method:path:uriTemplate` | 2.14 | Expose REST services or call external REST services.

| link:https://camel.apache.org/components/latest/rest-api-component.html[REST API] (camel-rest-starter) +
`rest-api:path/contextIdPattern` | 2.16 | Expose OpenAPI Specification of the REST services defined using Camel REST DSL.

| link:https://camel.apache.org/components/latest/rest-openapi-component.html[REST OpenApi] (camel-rest-openapi-starter) +
`rest-openapi:specificationUri#operationId` | 3.1 | Configure REST producers based on an OpenAPI specification document delegating to a component implementing the RestProducerFactory interface.

| link:https://camel.apache.org/components/latest/rest-swagger-component.html[REST Swagger] (camel-rest-swagger-starter) +
`rest-swagger:specificationUri#operationId` | 2.19 | Configure REST producers based on a Swagger (OpenAPI) specification document delegating to a component implementing the RestProducerFactory interface.

| link:https://camel.apache.org/components/latest/resteasy-component.html[Resteasy] (camel-resteasy-starter) +
`resteasy:httpUri` | 3.4 | Expose REST endpoints and access external REST servers.

| link:https://camel.apache.org/components/latest/robotframework-component.html[Robot Framework] (camel-robotframework-starter) +
`robotframework:resourceUri` | 3.0 | Pass camel exchanges to acceptence test written in Robot DSL.

| link:https://camel.apache.org/components/latest/rss-component.html[RSS] (camel-rss-starter) +
`rss:feedUri` | 2.0 | Poll RSS feeds.

| link:https://camel.apache.org/components/latest/saga-component.html[Saga] (camel-saga-starter) +
`saga:action` | 2.21 | Execute custom actions within a route using the Saga EIP.

| link:https://camel.apache.org/components/latest/salesforce-component.html[Salesforce] (camel-salesforce-starter) +
`salesforce:operationName:topicName` | 2.12 | Communicate with Salesforce using Java DTOs.

| link:https://camel.apache.org/components/latest/sap-netweaver-component.html[SAP NetWeaver] (camel-sap-netweaver-starter) +
`sap-netweaver:url` | 2.12 | Send requests to SAP NetWeaver Gateway using HTTP.

| link:https://camel.apache.org/components/latest/scheduler-component.html[Scheduler] (camel-scheduler-starter) +
`scheduler:name` | 2.15 | Generate messages in specified intervals using java.util.concurrent.ScheduledExecutorService.

| link:https://camel.apache.org/components/latest/schematron-component.html[Schematron] (camel-schematron-starter) +
`schematron:path` | 2.15 | Validate XML payload using the Schematron Library.

| link:https://camel.apache.org/components/latest/scp-component.html[SCP] (camel-jsch-starter) +
`scp:host:port/directoryName` | 2.10 | Copy files to/from remote hosts using the secure copy protocol (SCP).

| link:https://camel.apache.org/components/latest/seda-component.html[SEDA] (camel-seda-starter) +
`seda:name` | 1.1 | Asynchronously call another endpoint from any Camel Context in the same JVM.

| link:https://camel.apache.org/components/latest/service-component.html[Service] (camel-service-starter) +
`service:delegateUri` | 2.22 | Register a Camel endpoint to a Service Registry (such as Consul, Etcd) and delegate to it.

| link:https://camel.apache.org/components/latest/servicenow-component.html[ServiceNow] (camel-servicenow-starter) +
`servicenow:instanceName` | 2.18 | Interact with ServiceNow via its REST API.

| link:https://camel.apache.org/components/latest/servlet-component.html[Servlet] (camel-servlet-starter) +
`servlet:contextPath` | 2.0 | Serve HTTP requests by a Servlet.

| link:https://camel.apache.org/components/latest/sftp-component.html[SFTP] (camel-ftp-starter) +
`sftp:host:port/directoryName` | 1.1 | Upload and download files to/from SFTP servers.

| link:https://camel.apache.org/components/latest/sjms-component.html[Simple JMS] (camel-sjms-starter) +
`sjms:destinationType:destinationName` | 2.11 | Send and receive messages to/from a JMS Queue or Topic using plain JMS 1.x API.

| link:https://camel.apache.org/components/latest/sjms-batch-component.html[Simple JMS Batch] (camel-sjms-starter) +
`sjms-batch:destinationName` | 2.16 | Highly performant and transactional batch consumption of messages from a JMS queue.

| link:https://camel.apache.org/components/latest/sjms2-component.html[Simple JMS2] (camel-sjms2-starter) +
`sjms2:destinationType:destinationName` | 2.19 | Send and receive messages to/from a JMS Queue or Topic using plain JMS 2.x API.

| link:https://camel.apache.org/components/latest/sip-component.html[SIP] (camel-sip-starter) +
`sip:uri` | 2.5 | Send and receive messages using the SIP protocol (used in telecommunications).

| link:https://camel.apache.org/components/latest/slack-component.html[Slack] (camel-slack-starter) +
`slack:channel` | 2.16 | Send and receive messages to/from Slack.

| link:https://camel.apache.org/components/latest/smpp-component.html[SMPP] (camel-smpp-starter) +
`smpp:host:port` | 2.2 | Send and receive SMS messages using a SMSC (Short Message Service Center).

| link:https://camel.apache.org/components/latest/snmp-component.html[SNMP] (camel-snmp-starter) +
`snmp:host:port` | 2.1 | Receive traps and poll SNMP (Simple Network Management Protocol) capable devices.

| link:https://camel.apache.org/components/latest/solr-component.html[Solr] (camel-solr-starter) +
`solr:url` | 2.9 | Perform operations against Apache Lucene Solr.

| link:https://camel.apache.org/components/latest/soroush-component.html[Soroush] (camel-soroush-starter) +
`soroush:action` | 3.0 | Send and receive messages as a Soroush chat bot.

| link:https://camel.apache.org/components/latest/spark-component.html[Spark] (camel-spark-starter) +
`spark:endpointType` | 2.17 | Send RDD or DataFrame jobs to Apache Spark clusters.

| link:https://camel.apache.org/components/latest/splunk-component.html[Splunk] (camel-splunk-starter) +
`splunk:name` | 2.13 | Publish or search for events in Splunk.

| link:https://camel.apache.org/components/latest/spring-batch-component.html[Spring Batch] (camel-spring-batch-starter) +
`spring-batch:jobName` | 2.10 | Send messages to Spring Batch for further processing.

| link:https://camel.apache.org/components/latest/spring-event-component.html[Spring Event] (camel-spring-starter) +
`spring-event:name` | 1.4 | Listen for Spring Application Events.

| link:https://camel.apache.org/components/latest/spring-integration-component.html[Spring Integration] (camel-spring-integration-starter) +
`spring-integration:defaultChannel` | 1.4 | Bridge Camel with Spring Integration.

| link:https://camel.apache.org/components/latest/spring-ldap-component.html[Spring LDAP] (camel-spring-ldap-starter) +
`spring-ldap:templateName` | 2.11 | Perform searches in LDAP servers using filters as the message payload.

| link:https://camel.apache.org/components/latest/spring-redis-component.html[Spring Redis] (camel-spring-redis-starter) +
`spring-redis:host:port` | 2.11 | Send and receive messages from Redis.

| link:https://camel.apache.org/components/latest/spring-ws-component.html[Spring WebService] (camel-spring-ws-starter) +
`spring-ws:type:lookupKey:webServiceEndpointUri` | 2.6 | Access external web services as a client or expose your own web services.

| link:https://camel.apache.org/components/latest/sql-component.html[SQL] (camel-sql-starter) +
`sql:query` | 1.4 | Perform SQL queries using Spring JDBC.

| link:https://camel.apache.org/components/latest/sql-stored-component.html[SQL Stored Procedure] (camel-sql-starter) +
`sql-stored:template` | 2.17 | Perform SQL queries as a JDBC Stored Procedures using Spring JDBC.

| link:https://camel.apache.org/components/latest/ssh-component.html[SSH] (camel-ssh-starter) +
`ssh:host:port` | 2.10 | Execute commands on remote hosts using SSH.

| link:https://camel.apache.org/components/latest/stax-component.html[StAX] (camel-stax-starter) +
`stax:contentHandlerClass` | 2.9 | Process XML payloads by a SAX ContentHandler.

| link:https://camel.apache.org/components/latest/stomp-component.html[Stomp] (camel-stomp-starter) +
`stomp:destination` | 2.12 | Send and rececive messages to/from STOMP (Simple Text Oriented Messaging Protocol) compliant message brokers.

| link:https://camel.apache.org/components/latest/stream-component.html[Stream] (camel-stream-starter) +
`stream:kind` | 1.3 | Read from system-in and write to system-out and system-err streams.

| link:https://camel.apache.org/components/latest/string-template-component.html[String Template] (camel-stringtemplate-starter) +
`string-template:resourceUri` | 1.2 | Transform messages using StringTemplate engine.

| link:https://camel.apache.org/components/latest/stub-component.html[Stub] (camel-stub-starter) +
`stub:name` | 2.10 | Stub out any physical endpoints while in development or testing.

| link:https://camel.apache.org/components/latest/telegram-component.html[Telegram] (camel-telegram-starter) +
`telegram:type` | 2.18 | Send and receive messages acting as a Telegram Bot Telegram Bot API.

| link:https://camel.apache.org/components/latest/thrift-component.html[Thrift] (camel-thrift-starter) +
`thrift:host:port/service` | 2.20 | Call and expose remote procedures (RPC) with Apache Thrift data format and serialization mechanism.

| link:https://camel.apache.org/components/latest/tika-component.html[Tika] (camel-tika-starter) +
`tika:operation` | 2.19 | Parse documents and extract metadata and text using Apache Tika.

| link:https://camel.apache.org/components/latest/timer-component.html[Timer] (camel-timer-starter) +
`timer:timerName` | 1.0 | Generate messages in specified intervals using java.util.Timer.

| link:https://camel.apache.org/components/latest/twilio-component.html[Twilio] (camel-twilio-starter) +
`twilio:apiName/methodName` | 2.20 | Interact with Twilio REST APIs using Twilio Java SDK.

| link:https://camel.apache.org/components/latest/twitter-directmessage-component.html[Twitter Direct Message] (camel-twitter-starter) +
`twitter-directmessage:user` | 2.10 | Send and receive Twitter direct messages.

| link:https://camel.apache.org/components/latest/twitter-search-component.html[Twitter Search] (camel-twitter-starter) +
`twitter-search:keywords` | 2.10 | Access Twitter Search.

| link:https://camel.apache.org/components/latest/twitter-timeline-component.html[Twitter Timeline] (camel-twitter-starter) +
`twitter-timeline:timelineType` | 2.10 | Send tweets and receive tweets from user's timeline.

| link:https://camel.apache.org/components/latest/undertow-component.html[Undertow] (camel-undertow-starter) +
`undertow:httpURI` | 2.16 | Expose HTTP and WebSocket endpoints and access external HTTP/WebSocket servers.

| link:https://camel.apache.org/components/latest/validator-component.html[Validator] (camel-validator-starter) +
`validator:resourceUri` | 1.1 | Validate the payload using XML Schema and JAXP Validation.

| link:https://camel.apache.org/components/latest/velocity-component.html[Velocity] (camel-velocity-starter) +
`velocity:resourceUri` | 1.2 | Transform messages using a Velocity template.

| link:https://camel.apache.org/components/latest/vertx-component.html[Vert.x] (camel-vertx-starter) +
`vertx:address` | 2.12 | Send and receive messages to/from Vert.x Event Bus.

| link:https://camel.apache.org/components/latest/vertx-http-component.html[Vert.x HTTP Client] (camel-vertx-http-starter) +
`vertx-http:httpUri` | 3.5 | Camel HTTP client support with Vert.x

| link:https://camel.apache.org/components/latest/vertx-websocket-component.html[Vert.x WebSocket] (camel-vertx-websocket-starter) +
`vertx-websocket:host:port/path` | 3.5 | Camel WebSocket support with Vert.x

| link:https://camel.apache.org/components/latest/vm-component.html[VM] (camel-vm-starter) +
`vm:name` | 1.1 | Call another endpoint in the same CamelContext asynchronously.

| link:https://camel.apache.org/components/latest/weather-component.html[Weather] (camel-weather-starter) +
`weather:name` | 2.12 | Poll the weather information from Open Weather Map.

| link:https://camel.apache.org/components/latest/web3j-component.html[Web3j Ethereum Blockchain] (camel-web3j-starter) +
`web3j:nodeAddress` | 2.22 | Interact with Ethereum nodes using web3j client API.

| link:https://camel.apache.org/components/latest/webhook-component.html[Webhook] (camel-webhook-starter) +
`webhook:endpointUri` | 3.0 | Expose webhook endpoints to receive push notifications for other Camel components.

| link:https://camel.apache.org/components/latest/weka-component.html[Weka] (camel-weka-starter) +
`weka:command` | 3.1 | Perform machine learning tasks using Weka.

| link:https://camel.apache.org/components/latest/wordpress-component.html[Wordpress] (camel-wordpress-starter) +
`wordpress:operation` | 2.21 | Manage posts and users using Wordpress API.

| link:https://camel.apache.org/components/latest/workday-component.html[Workday] (camel-workday-starter) +
`workday:entity:path` | 3.1 | Detect and parse documents using Workday.

| link:https://camel.apache.org/components/latest/xchange-component.html[XChange] (camel-xchange-starter) +
`xchange:name` | 2.21 | Access market data and trade on Bitcoin and Altcoin exchanges.

| link:https://camel.apache.org/components/latest/xj-component.html[XJ] (camel-xj-starter) +
`xj:resourceUri` | 3.0 | Transform JSON and XML message using a XSLT.

| link:https://camel.apache.org/components/latest/xmlsecurity-sign-component.html[XML Security Sign] (camel-xmlsecurity-starter) +
`xmlsecurity-sign:name` | 2.12 | Sign XML payloads using the XML signature specification.

| link:https://camel.apache.org/components/latest/xmlsecurity-verify-component.html[XML Security Verify] (camel-xmlsecurity-starter) +
`xmlsecurity-verify:name` | 2.12 | Verify XML payloads using the XML signature specification.

| link:https://camel.apache.org/components/latest/xmpp-component.html[XMPP] (camel-xmpp-starter) +
`xmpp:host:port/participant` | 1.0 | Send and receive messages to/from an XMPP chat server.

| link:https://camel.apache.org/components/latest/xquery-component.html[XQuery] (camel-saxon-starter) +
`xquery:resourceUri` | 1.0 | Query and/or transform XML payloads using XQuery and Saxon.

| link:https://camel.apache.org/components/latest/xslt-component.html[XSLT] (camel-xslt-starter) +
`xslt:resourceUri` | 1.3 | Transforms XML payload using an XSLT template.

| link:https://camel.apache.org/components/latest/xslt-saxon-component.html[XSLT Saxon] (camel-xslt-saxon-starter) +
`xslt-saxon:resourceUri` | 3.0 | Transform XML payloads using an XSLT template using Saxon.

| link:https://camel.apache.org/components/latest/yammer-component.html[Yammer] (camel-yammer-starter) +
`yammer:function` | 2.12 | Interact with the Yammer enterprise social network.

| link:https://camel.apache.org/components/latest/zendesk-component.html[Zendesk] (camel-zendesk-starter) +
`zendesk:methodName` | 2.19 | Manage Zendesk tickets, users, organizations, etc.

| link:https://camel.apache.org/components/latest/zookeeper-component.html[ZooKeeper] (camel-zookeeper-starter) +
`zookeeper:serverUrls/path` | 2.9 | Manage ZooKeeper clusters.

| link:https://camel.apache.org/components/latest/zookeeper-master-component.html[ZooKeeper Master] (camel-zookeeper-master-starter) +
`zookeeper-master:groupName:consumerEndpointUri` | 2.19 | Have only a single consumer in a cluster consuming from a given endpoint; with automatic failover if the JVM dies.

|===
// components: END

== Camel Data Formats

// dataformats: START
Number of Camel data formats: 45 in 37 JAR artifacts (0 deprecated)

[width="100%",cols="4,1,5",options="header"]
|===
| Data Format | Since | Description

| link:https://camel.apache.org/components/latest/dataformats/any23-dataformat.html[Any23] +
(camel-any23-starter) | 3.0 | Extract RDF data from HTML documents.

| link:https://camel.apache.org/components/latest/dataformats/asn1-dataformat.html[ASN.1 File] +
(camel-asn1-starter) | 2.20 | Encode and decode data structures using Abstract Syntax Notation One (ASN.1).

| link:https://camel.apache.org/components/latest/dataformats/avro-dataformat.html[Avro] +
(camel-avro-starter) | 2.14 | Serialize and deserialize messages using Apache Avro binary data format.

| link:https://camel.apache.org/components/latest/dataformats/barcode-dataformat.html[Barcode] +
(camel-barcode-starter) | 2.14 | Transform strings to various 1D/2D barcode bitmap formats and back.

| link:https://camel.apache.org/components/latest/dataformats/base64-dataformat.html[Base64] +
(camel-base64-starter) | 2.11 | Encode and decode data using Base64.

| link:https://camel.apache.org/components/latest/dataformats/beanio-dataformat.html[BeanIO] +
(camel-beanio-starter) | 2.10 | Marshal and unmarshal Java beans to and from flat files (such as CSV, delimited, or fixed length formats).

| link:https://camel.apache.org/components/latest/dataformats/bindy-dataformat.html[Bindy CSV] +
(camel-bindy-starter) | 2.0 | Marshal and unmarshal Java beans from and to flat payloads (such as CSV, delimited, fixed length formats, or FIX messages).

| link:https://camel.apache.org/components/latest/dataformats/bindy-dataformat.html[Bindy Fixed Length] +
(camel-bindy-starter) | 2.0 | Marshal and unmarshal Java beans from and to flat payloads (such as CSV, delimited, fixed length formats, or FIX messages).

| link:https://camel.apache.org/components/latest/dataformats/bindy-dataformat.html[Bindy Key Value Pair] +
(camel-bindy-starter) | 2.0 | Marshal and unmarshal Java beans from and to flat payloads (such as CSV, delimited, fixed length formats, or FIX messages).

| link:https://camel.apache.org/components/latest/dataformats/cbor-dataformat.html[CBOR] +
(camel-cbor-starter) | 3.0 | Unmarshal a CBOR payload to POJO and back.

| link:https://camel.apache.org/components/latest/dataformats/crypto-dataformat.html[Crypto (Java Cryptographic Extension)] +
(camel-crypto-starter) | 2.3 | Encrypt and decrypt messages using Java Cryptography Extension (JCE).

| link:https://camel.apache.org/components/latest/dataformats/csv-dataformat.html[CSV] +
(camel-csv-starter) | 1.3 | Handle CSV (Comma Separated Values) payloads.

| link:https://camel.apache.org/components/latest/dataformats/fhirJson-dataformat.html[FHIR JSon] +
(camel-fhir-starter) | 2.21 | Marshall and unmarshall FHIR objects to/from JSON.

| link:https://camel.apache.org/components/latest/dataformats/fhirXml-dataformat.html[FHIR XML] +
(camel-fhir-starter) | 2.21 | Marshall and unmarshall FHIR objects to/from XML.

| link:https://camel.apache.org/components/latest/dataformats/flatpack-dataformat.html[Flatpack] +
(camel-flatpack-starter) | 2.1 | Marshal and unmarshal Java lists and maps to/from flat files (such as CSV, delimited, or fixed length formats) using Flatpack library.

| link:https://camel.apache.org/components/latest/dataformats/grok-dataformat.html[Grok] +
(camel-grok-starter) | 3.0 | Unmarshal unstructured data to objects using Logstash based Grok patterns.

| link:https://camel.apache.org/components/latest/dataformats/gzipdeflater-dataformat.html[GZip Deflater] +
(camel-zip-deflater-starter) | 2.0 | Compress and decompress messages using java.util.zip.GZIPStream.

| link:https://camel.apache.org/components/latest/dataformats/hl7-dataformat.html[HL7] +
(camel-hl7-starter) | 2.0 | Marshal and unmarshal HL7 (Health Care) model objects using the HL7 MLLP codec.

| link:https://camel.apache.org/components/latest/dataformats/ical-dataformat.html[iCal] +
(camel-ical-starter) | 2.12 | Marshal and unmarshal iCal (.ics) documents to/from model objects provided by the iCal4j library.

| link:https://camel.apache.org/components/latest/dataformats/jacksonxml-dataformat.html[JacksonXML] +
(camel-jacksonxml-starter) | 2.16 | Unmarshal a XML payloads to POJOs and back using XMLMapper extension of Jackson.

| link:https://camel.apache.org/components/latest/dataformats/jaxb-dataformat.html[JAXB] +
(camel-jaxb-starter) | 1.0 | Unmarshal XML payloads to POJOs and back using JAXB2 XML marshalling standard.

| link:https://camel.apache.org/components/latest/dataformats/json-fastjson-dataformat.html[JSON Fastjson] +
(camel-fastjson-starter) | 2.20 | Marshal POJOs to JSON and back.

| link:https://camel.apache.org/components/latest/dataformats/json-gson-dataformat.html[JSON Gson] +
(camel-gson-starter) | 2.10 | Marshal POJOs to JSON and back.

| link:https://camel.apache.org/components/latest/dataformats/json-jackson-dataformat.html[JSON Jackson] +
(camel-jackson-starter) | 2.0 | Marshal POJOs to JSON and back.

| link:https://camel.apache.org/components/latest/dataformats/json-johnzon-dataformat.html[JSON Johnzon] +
(camel-johnzon-starter) | 2.18 | Marshal POJOs to JSON and back.

| link:https://camel.apache.org/components/latest/dataformats/json-xstream-dataformat.html[JSON XStream] +
(camel-xstream-starter) | 2.0 | Marshal POJOs to JSON and back.

| link:https://camel.apache.org/components/latest/dataformats/jsonApi-dataformat.html[JSonApi] +
(camel-jsonapi-starter) | 3.0 | Marshal and unmarshal JSON:API resources using JSONAPI-Converter library.

| link:https://camel.apache.org/components/latest/dataformats/lzf-dataformat.html[LZF Deflate Compression] +
(camel-lzf-starter) | 2.17 | Compress and decompress streams using LZF deflate algorithm.

| link:https://camel.apache.org/components/latest/dataformats/mime-multipart-dataformat.html[MIME Multipart] +
(camel-mail-starter) | 2.17 | Marshal Camel messages with attachments into MIME-Multipart messages and back.

| link:https://camel.apache.org/components/latest/dataformats/pgp-dataformat.html[PGP] +
(camel-crypto-starter) | 2.9 | Encrypt and decrypt messages using Java Cryptographic Extension (JCE) and PGP.

| link:https://camel.apache.org/components/latest/dataformats/protobuf-dataformat.html[Protobuf] +
(camel-protobuf-starter) | 2.2 | Serialize and deserialize Java objects using Google's Protocol buffers.

| link:https://camel.apache.org/components/latest/dataformats/rss-dataformat.html[RSS] +
(camel-rss-starter) | 2.1 | Transform from ROME SyndFeed Java Objects to XML and vice-versa.

| link:https://camel.apache.org/components/latest/dataformats/soapjaxb-dataformat.html[SOAP] +
(camel-soap-starter) | 2.3 | Marshal Java objects to SOAP messages and back.

| link:https://camel.apache.org/components/latest/dataformats/syslog-dataformat.html[Syslog] +
(camel-syslog-starter) | 2.6 | Marshall SyslogMessages to RFC3164 and RFC5424 messages and back.

| link:https://camel.apache.org/components/latest/dataformats/tarfile-dataformat.html[Tar File] +
(camel-tarfile-starter) | 2.16 | Archive files into tarballs or extract files from tarballs.

| link:https://camel.apache.org/components/latest/dataformats/thrift-dataformat.html[Thrift] +
(camel-thrift-starter) | 2.20 | Serialize and deserialize messages using Apache Thrift binary data format.

| link:https://camel.apache.org/components/latest/dataformats/tidyMarkup-dataformat.html[TidyMarkup] +
(camel-tagsoup-starter) | 2.0 | Parse (potentially invalid) HTML into valid HTML or DOM.

| link:https://camel.apache.org/components/latest/dataformats/univocity-csv-dataformat.html[uniVocity CSV] +
(camel-univocity-parsers-starter) | 2.15 | Marshal and unmarshal Java objects from and to CSV (Comma Separated Values) using UniVocity Parsers.

| link:https://camel.apache.org/components/latest/dataformats/univocity-fixed-dataformat.html[uniVocity Fixed Length] +
(camel-univocity-parsers-starter) | 2.15 | Marshal and unmarshal Java objects from and to fixed length records using UniVocity Parsers.

| link:https://camel.apache.org/components/latest/dataformats/univocity-tsv-dataformat.html[uniVocity TSV] +
(camel-univocity-parsers-starter) | 2.15 | Marshal and unmarshal Java objects from and to TSV (Tab-Separated Values) records using UniVocity Parsers.

| link:https://camel.apache.org/components/latest/dataformats/secureXML-dataformat.html[XML Security] +
(camel-xmlsecurity-starter) | 2.0 | Encrypt and decrypt XML payloads using Apache Santuario.

| link:https://camel.apache.org/components/latest/dataformats/xstream-dataformat.html[XStream] +
(camel-xstream-starter) | 1.3 | Marshal and unmarshal POJOs to/from XML using XStream library.

| link:https://camel.apache.org/components/latest/dataformats/yaml-snakeyaml-dataformat.html[YAML SnakeYAML] +
(camel-snakeyaml-starter) | 2.17 | Marshal and unmarshal Java objects to and from YAML.

| link:https://camel.apache.org/components/latest/dataformats/zipdeflater-dataformat.html[Zip Deflate Compression] +
(camel-zip-deflater-starter) | 2.12 | Compress and decompress streams using java.util.zip.Deflater and java.util.zip.Inflater.

| link:https://camel.apache.org/components/latest/dataformats/zipfile-dataformat.html[Zip File] +
(camel-zipfile-starter) | 2.11 | Compression and decompress streams using java.util.zip.ZipStream.
|===
// dataformats: END

== Camel Languages

// languages: START
Number of Camel languages: 17 in 11 JAR artifacts (0 deprecated)

[width="100%",cols="4,1,5",options="header"]
|===
| Language | Since | Description

| link:https://camel.apache.org/components/latest/languages/bean-language.html[Bean method] +
(camel-bean-starter) | 1.3 | Call a method of the specified Java bean passing the Exchange, Body or specific headers to it.

| link:https://camel.apache.org/components/latest/languages/constant-language.html[Constant] +
(camel-base) | 1.5 | To use a constant value in Camel expressions or predicates. Important: this is a fixed constant value that is only set once during starting up the route, do not use this if you want dynamic values during routing.

| link:https://camel.apache.org/components/latest/languages/exchangeProperty-language.html[ExchangeProperty] +
(camel-base) | 2.0 | To use a Camel Exchange property in expressions or predicates.

| link:https://camel.apache.org/components/latest/languages/file-language.html[File] +
(camel-base) | 1.1 | For expressions and predicates using the file/simple language.

| link:https://camel.apache.org/components/latest/languages/groovy-language.html[Groovy] +
(camel-groovy-starter) | 1.3 | Evaluate a Groovy script.

| link:https://camel.apache.org/components/latest/languages/header-language.html[Header] +
(camel-base) | 1.5 | To use a Camel Message header in expressions or predicates.

| link:https://camel.apache.org/components/latest/languages/hl7terser-language.html[HL7 Terser] +
(camel-hl7-starter) | 2.11 | Get the value of an HL7 message field specified by terse location specification syntax.

| link:https://camel.apache.org/components/latest/languages/jsonpath-language.html[JsonPath] +
(camel-jsonpath-starter) | 2.13 | Evaluate a JsonPath expression against a JSON message body.

| link:https://camel.apache.org/components/latest/languages/mvel-language.html[MVEL] +
(camel-mvel-starter) | 2.0 | Evaluate an MVEL template against the Camel Exchange.

| link:https://camel.apache.org/components/latest/languages/ognl-language.html[OGNL] +
(camel-ognl-starter) | 1.1 | Evaluate an Apache Commons Object Graph Navigation Library (OGNL) expression against the Camel Exchange.

| link:https://camel.apache.org/components/latest/languages/ref-language.html[Ref] +
(camel-base) | 2.8 | Reference to an existing Camel expression or predicate, which is looked up from the Camel registry.

| link:https://camel.apache.org/components/latest/languages/simple-language.html[Simple] +
(camel-base) | 1.1 | To use Camels built-in Simple language in Camel expressions or predicates.

| link:https://camel.apache.org/components/latest/languages/spel-language.html[SpEL] +
(camel-spring-starter) | 2.7 | Evaluate a Spring Expression Language (SpEL) expression against the Camel Exchange.

| link:https://camel.apache.org/components/latest/languages/tokenize-language.html[Tokenize] +
(camel-base) | 2.0 | To use Camel message body or header with a tokenizer in Camel expressions or predicates.

| link:https://camel.apache.org/components/latest/languages/xtokenize-language.html[XML Tokenize] +
(camel-xml-jaxp-starter) | 2.14 | Tokenize XML payloads using the specified path expression.

| link:https://camel.apache.org/components/latest/languages/xpath-language.html[XPath] +
(camel-xpath-starter) | 1.1 | Evaluate an XPath expression against an XML payload.

| link:https://camel.apache.org/components/latest/languages/xquery-language.html[XQuery] +
(camel-saxon-starter) | 1.0 | Evaluate an XQuery expressions against an XML payload.
|===
// languages: END


== Miscellaneous Extensions

// others: START
Number of miscellaneous extensions: 23 in 23 JAR artifacts (1 deprecated)

[width="100%",cols="4,1,5",options="header"]
|===
| Extension | Since | Description

| link:https://camel.apache.org/components/latest/others/aws-xray.html[AWS XRay] +
(camel-aws-xray-starter) | 2.21 | Distributed tracing using AWS XRay

| link:https://camel.apache.org/components/latest/others/cxf-transport.html[CXF Transport] +
(camel-cxf-transport-starter) | 2.8 | Camel Transport for Apache CXF

| link:https://camel.apache.org/components/latest/others/hystrix.html[Hystrix] +
(camel-hystrix-starter) | 2.18 | *deprecated* Circuit Breaker EIP using Netflix Hystrix

| link:https://camel.apache.org/components/latest/others/jasypt.html[Jasypt] +
(camel-jasypt-starter) | 2.5 | Security using Jasypt

| link:https://camel.apache.org/components/latest/others/leveldb.html[LevelDB] +
(camel-leveldb-starter) | 2.10 | Using LevelDB as persistent EIP store

| link:https://camel.apache.org/components/latest/others/lra.html[LRA] +
(camel-lra-starter) | 2.21 | Camel saga binding for Long-Running-Action framework

| link:https://camel.apache.org/components/latest/others/openapi-java.html[Openapi Java] +
(camel-openapi-java-starter) | 3.1 | Rest-dsl support for using openapi doc

| link:https://camel.apache.org/components/latest/others/opentelemetry.html[OpenTelemetry] +
(camel-opentelemetry-starter) | 3.5 | Distributed tracing using OpenTelemetry

| link:https://camel.apache.org/components/latest/others/opentracing.html[OpenTracing] +
(camel-opentracing-starter) | 2.19 | Distributed tracing using OpenTracing

| link:https://camel.apache.org/components/latest/others/reactor.html[Reactor] +
(camel-reactor-starter) | 2.20 | Reactor based back-end for Camel's reactive streams component

| link:https://camel.apache.org/components/latest/others/resilience4j.html[Resilience4j] +
(camel-resilience4j-starter) | 3.0 | Circuit Breaker EIP using Resilience4j

| link:https://camel.apache.org/components/latest/others/ribbon.html[Ribbon] +
(camel-ribbon-starter) | 2.18 | Using Netflix Ribbon for client side load balancing

| link:https://camel.apache.org/components/latest/others/rxjava.html[RxJava] +
(camel-rxjava-starter) | 2.22 | RxJava based back-end for Camel's reactive streams component

| link:https://camel.apache.org/components/latest/others/shiro.html[Shiro] +
(camel-shiro-starter) | 2.5 | Security using Shiro

| link:https://camel.apache.org/components/latest/others/spring-cloud.html[Spring Cloud] +
(camel-spring-cloud-starter) | 2.19 | Camel Cloud integration with Spring Cloud

| link:https://camel.apache.org/components/latest/others/spring-cloud-consul.html[Spring Cloud Consul] +
(camel-spring-cloud-consul-starter) | 2.19 | Camel Cloud integration with Spring Cloud Consul

| link:https://camel.apache.org/components/latest/others/spring-cloud-netflix.html[Spring Cloud Netflix] +
(camel-spring-cloud-netflix-starter) | 2.19 | Camel Cloud integration with Spring Cloud Netflix

| link:https://camel.apache.org/components/latest/others/spring-cloud-zookeeper.html[Spring Cloud Zookeeper] +
(camel-spring-cloud-zookeeper-starter) | 2.19 | Camel Cloud integration with Spring Cloud Zookeeper

| link:https://camel.apache.org/components/latest/others/spring-javaconfig.html[Spring Java Configuration] +
(camel-spring-javaconfig-starter) | 2.0 | Using Camel with Spring Java Configuration

| link:https://camel.apache.org/components/latest/others/spring-security.html[Spring Security] +
(camel-spring-security-starter) | 2.3 | Security using Spring Security

| link:https://camel.apache.org/components/latest/others/swagger-java.html[Swagger Java] +
(camel-swagger-java-starter) | 2.16 | Rest-dsl support for using swagger api-doc

| link:https://camel.apache.org/components/latest/others/undertow-spring-security.html[Undertow Spring Security] +
(camel-undertow-spring-security-starter) | 3.3 | Spring Security Provider for camel-undertow

| link:https://camel.apache.org/components/latest/others/zipkin.html[Zipkin] +
(camel-zipkin-starter) | 2.18 | Distributed message tracing using Zipkin
|===
// others: END

