/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.component.spiffe.springboot;

import io.spiffe.workloadapi.WorkloadApiClient;
import org.apache.camel.component.spiffe.SpiffeComponent;
import org.apache.camel.component.spiffe.SpiffeConfiguration;
import org.apache.camel.component.spiffe.SpiffeOperation;
import org.apache.camel.spring.boot.ComponentConfigurationPropertiesCommon;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Fetch and validate SPIFFE workload identity (X.509-SVID and JWT-SVID) from
 * the SPIFFE Workload API.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "camel.component.spiffe")
public class SpiffeComponentConfiguration
        extends
            ComponentConfigurationPropertiesCommon {

    /**
     * Whether to enable auto configuration of the spiffe component. This is
     * enabled by default.
     */
    private Boolean enabled;
    /**
     * The comma-separated audience(s) to request for a JWT-SVID (fetchJwtSvid)
     * or to validate against (validateJwtSvid). fetchJwtSvid requests all of
     * them and can be overridden per-message with the CamelSpiffeAudience
     * header; validateJwtSvid ignores that header and uses this configuration
     * only, accepting the token if it matches any of the configured audiences,
     * trying each in turn.
     */
    private String audience;
    /**
     * The component configuration. The option is a
     * org.apache.camel.component.spiffe.SpiffeConfiguration type.
     */
    private SpiffeConfiguration configuration;
    /**
     * Whether the producer should be started lazy (on the first message). By
     * starting lazy you can use this to allow CamelContext and routes to
     * startup in situations where a producer may otherwise fail during starting
     * and cause the route to fail being started. By deferring this startup to
     * be lazy then the startup failure can be handled during routing messages
     * via Camel's routing error handlers. Beware that when the first message is
     * processed then creating and starting the producer may take a little time
     * and prolong the total processing time of the processing.
     */
    private Boolean lazyStartProducer = false;
    /**
     * The operation to perform on the SPIFFE Workload API.
     */
    private SpiffeOperation operation = SpiffeOperation.fetchX509Svid;
    /**
     * Whether autowiring is enabled. This is used for automatic autowiring
     * options (the option must be marked as autowired) by looking up in the
     * registry to find if there is a single instance of matching type, which
     * then gets configured on the component. This can be used for automatic
     * configuring JDBC data sources, JMS connection factories, AWS Clients,
     * etc.
     */
    private Boolean autowiredEnabled = true;
    /**
     * An existing WorkloadApiClient to use. When set, the component does not
     * create or close its own client and spiffeSocketPath is ignored. The
     * option is a io.spiffe.workloadapi.WorkloadApiClient type.
     */
    private WorkloadApiClient workloadApiClient;
    /**
     * Whether the CamelSpiffeOperation header may override the configured
     * operation. Disabled by default: the operation decides whether this
     * endpoint validates a token or mints one, so a message that can set it can
     * turn a validator into an endpoint that hands out this workload's own
     * JWT-SVID. Enable it only on routes whose input is trusted.
     */
    private Boolean allowOperationHeader = false;
    /**
     * The address of the SPIFFE Workload API endpoint (for example {code
     * unix:///tmp/agent.sock} or {code tcp://127.0.0.1:8082}). When not set,
     * the SPIFFE_ENDPOINT_SOCKET environment variable is used.
     */
    private String spiffeSocketPath;

    public String getAudience() {
        return audience;
    }

    public void setAudience(String audience) {
        this.audience = audience;
    }

    public SpiffeConfiguration getConfiguration() {
        return configuration;
    }

    public void setConfiguration(SpiffeConfiguration configuration) {
        this.configuration = configuration;
    }

    public Boolean getLazyStartProducer() {
        return lazyStartProducer;
    }

    public void setLazyStartProducer(Boolean lazyStartProducer) {
        this.lazyStartProducer = lazyStartProducer;
    }

    public SpiffeOperation getOperation() {
        return operation;
    }

    public void setOperation(SpiffeOperation operation) {
        this.operation = operation;
    }

    public Boolean getAutowiredEnabled() {
        return autowiredEnabled;
    }

    public void setAutowiredEnabled(Boolean autowiredEnabled) {
        this.autowiredEnabled = autowiredEnabled;
    }

    public WorkloadApiClient getWorkloadApiClient() {
        return workloadApiClient;
    }

    public void setWorkloadApiClient(WorkloadApiClient workloadApiClient) {
        this.workloadApiClient = workloadApiClient;
    }

    public Boolean getAllowOperationHeader() {
        return allowOperationHeader;
    }

    public void setAllowOperationHeader(Boolean allowOperationHeader) {
        this.allowOperationHeader = allowOperationHeader;
    }

    public String getSpiffeSocketPath() {
        return spiffeSocketPath;
    }

    public void setSpiffeSocketPath(String spiffeSocketPath) {
        this.spiffeSocketPath = spiffeSocketPath;
    }
}