/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.component.langchain4j.embeddings.springboot;

import java.time.Duration;
import java.util.Map;
import dev.langchain4j.model.embedding.EmbeddingModel;
import org.apache.camel.component.langchain4j.embeddings.LangChain4jEmbeddingsConfiguration;
import org.apache.camel.spring.boot.ComponentConfigurationPropertiesCommon;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * LangChain4j Embeddings
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "camel.component.langchain4j-embeddings")
public class LangChain4jEmbeddingsComponentConfiguration
        extends
            ComponentConfigurationPropertiesCommon {

    /**
     * Whether to enable auto configuration of the langchain4j-embeddings
     * component. This is enabled by default.
     */
    private Boolean enabled;
    /**
     * The configuration. The option is a
     * org.apache.camel.component.langchain4j.embeddings.LangChain4jEmbeddingsConfiguration type.
     */
    private LangChain4jEmbeddingsConfiguration configuration;
    /**
     * The EmbeddingModel engine to use. Either this or a provider is required.
     * The option is a dev.langchain4j.model.embedding.EmbeddingModel type.
     */
    private EmbeddingModel embeddingModel;
    /**
     * Whether the producer should be started lazy (on the first message). By
     * starting lazy you can use this to allow CamelContext and routes to
     * startup in situations where a producer may otherwise fail during starting
     * and cause the route to fail being started. By deferring this startup to
     * be lazy then the startup failure can be handled during routing messages
     * via Camel's routing error handlers. Beware that when the first message is
     * processed then creating and starting the producer may take a little time
     * and prolong the total processing time of the processing.
     */
    private Boolean lazyStartProducer = false;
    /**
     * Whether autowiring is enabled. This is used for automatic autowiring
     * options (the option must be marked as autowired) by looking up in the
     * registry to find if there is a single instance of matching type, which
     * then gets configured on the component. This can be used for automatic
     * configuring JDBC data sources, JMS connection factories, AWS Clients,
     * etc.
     */
    private Boolean autowiredEnabled = true;
    /**
     * The URL of the provider's API (http://localhost:11434 for a local
     * Ollama), when the model is created from the provider. The provider's
     * default when not set.
     */
    private String baseUrl;
    /**
     * The name of the model at the provider (qwen2.5, gpt-4o-mini, ...), when
     * the model is created from the provider.
     */
    private String modelName;
    /**
     * The LangChain4j provider of the embedding model, to create the model from
     * the options here (modelName, baseUrl, apiKey, temperature, timeout, and
     * provider-specific model. properties) instead of a EmbeddingModel bean.
     * The LangChain4j module of the provider
     * (dev.langchain4j:langchain4j-ollama, ...) must be on the classpath; Camel
     * JBang downloads it. Ignored when a EmbeddingModel is configured. For a
     * provider not listed, set customProvider instead.
     */
    private String provider;
    /**
     * The sampling temperature of the model, when the model is created from the
     * provider.
     */
    private Double temperature;
    /**
     * The request timeout of the model (30s, 2m), when the model is created
     * from the provider.
     */
    private Duration timeout;
    /**
     * The fully qualified class name of the LangChain4j model class of a
     * provider that is not listed in provider
     * (dev.langchain4j.model.jlama.JlamaChatModel), created from the options
     * here through its builder() as a listed provider is. Set either provider
     * or customProvider.
     */
    private String customProvider;
    /**
     * Provider-specific properties of the model, set on the model's builder as
     * they are (model.numPredict=512 for Ollama, model.maxTokens=1024 for
     * OpenAI), when the model is created from the provider. This is a
     * multi-value option with prefix: model.
     */
    private Map<String, Object> modelProperties;
    /**
     * The API key or access token of the provider, when the model is created
     * from the provider.
     */
    private String apiKey;

    public LangChain4jEmbeddingsConfiguration getConfiguration() {
        return configuration;
    }

    public void setConfiguration(
            LangChain4jEmbeddingsConfiguration configuration) {
        this.configuration = configuration;
    }

    public EmbeddingModel getEmbeddingModel() {
        return embeddingModel;
    }

    public void setEmbeddingModel(EmbeddingModel embeddingModel) {
        this.embeddingModel = embeddingModel;
    }

    public Boolean getLazyStartProducer() {
        return lazyStartProducer;
    }

    public void setLazyStartProducer(Boolean lazyStartProducer) {
        this.lazyStartProducer = lazyStartProducer;
    }

    public Boolean getAutowiredEnabled() {
        return autowiredEnabled;
    }

    public void setAutowiredEnabled(Boolean autowiredEnabled) {
        this.autowiredEnabled = autowiredEnabled;
    }

    public String getBaseUrl() {
        return baseUrl;
    }

    public void setBaseUrl(String baseUrl) {
        this.baseUrl = baseUrl;
    }

    public String getModelName() {
        return modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public Double getTemperature() {
        return temperature;
    }

    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    public Duration getTimeout() {
        return timeout;
    }

    public void setTimeout(Duration timeout) {
        this.timeout = timeout;
    }

    public String getCustomProvider() {
        return customProvider;
    }

    public void setCustomProvider(String customProvider) {
        this.customProvider = customProvider;
    }

    public Map<String, Object> getModelProperties() {
        return modelProperties;
    }

    public void setModelProperties(Map<String, Object> modelProperties) {
        this.modelProperties = modelProperties;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }
}