/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.dataformat.tarfile.springboot;

import org.apache.camel.spring.boot.DataFormatConfigurationPropertiesCommon;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Archive files into tarballs or extract files from tarballs.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "camel.dataformat.tar-file")
public class TarFileDataFormatConfiguration
        extends
            DataFormatConfigurationPropertiesCommon {

    /**
     * Whether to enable auto configuration of the tarFile data format. This is
     * enabled by default.
     */
    private Boolean enabled;
    /**
     * Whether to use an iterator to split tar entries when the tar file has
     * more than one entry, for use with the splitter EIP in streaming mode.
     */
    private Boolean usingIterator = false;
    /**
     * Whether to allow getting the iterator even if the directory is empty,
     * when the tar file has more than one entry.
     */
    private Boolean allowEmptyDirectory = false;
    /**
     * Whether to preserve path elements when the file name contains path
     * elements in the tar file.
     */
    private Boolean preservePathElements = false;
    /**
     * The maximum decompressed size of a tar file (in bytes). An IOException is
     * thrown if the decompressed size exceeds this amount. Set to -1 to
     * disable.
     */
    private Long maxDecompressedSize = 1073741824L;

    public Boolean getUsingIterator() {
        return usingIterator;
    }

    public void setUsingIterator(Boolean usingIterator) {
        this.usingIterator = usingIterator;
    }

    public Boolean getAllowEmptyDirectory() {
        return allowEmptyDirectory;
    }

    public void setAllowEmptyDirectory(Boolean allowEmptyDirectory) {
        this.allowEmptyDirectory = allowEmptyDirectory;
    }

    public Boolean getPreservePathElements() {
        return preservePathElements;
    }

    public void setPreservePathElements(Boolean preservePathElements) {
        this.preservePathElements = preservePathElements;
    }

    public Long getMaxDecompressedSize() {
        return maxDecompressedSize;
    }

    public void setMaxDecompressedSize(Long maxDecompressedSize) {
        this.maxDecompressedSize = maxDecompressedSize;
    }
}