/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.component.cyberark.vault.springboot;

import org.apache.camel.component.cyberark.vault.CyberArkVaultConfiguration;
import org.apache.camel.component.cyberark.vault.client.ConjurClient;
import org.apache.camel.spring.boot.ComponentConfigurationPropertiesCommon;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Retrieve secrets from CyberArk Conjur Vault.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "camel.component.cyberark-vault")
public class CyberArkVaultComponentConfiguration
        extends
            ComponentConfigurationPropertiesCommon {

    /**
     * Whether to enable auto configuration of the cyberark-vault component.
     * This is enabled by default.
     */
    private Boolean enabled;
    /**
     * The CyberArk Conjur account name
     */
    private String account;
    /**
     * Path to the SSL certificate for verification
     */
    private String certificatePath;
    /**
     * Component configuration. The option is a
     * org.apache.camel.component.cyberark.vault.CyberArkVaultConfiguration
     * type.
     */
    private CyberArkVaultConfiguration configuration;
    /**
     * Reference to a ConjurClient instance in the registry. The option is a
     * org.apache.camel.component.cyberark.vault.client.ConjurClient type.
     */
    private ConjurClient conjurClient;
    /**
     * Whether the producer should be started lazy (on the first message). By
     * starting lazy you can use this to allow CamelContext and routes to
     * startup in situations where a producer may otherwise fail during starting
     * and cause the route to fail being started. By deferring this startup to
     * be lazy then the startup failure can be handled during routing messages
     * via Camel's routing error handlers. Beware that when the first message is
     * processed then creating and starting the producer may take a little time
     * and prolong the total processing time of the processing.
     */
    private Boolean lazyStartProducer = false;
    /**
     * The secret ID to retrieve from CyberArk Conjur
     */
    private String secretId;
    /**
     * The CyberArk Conjur instance URL
     */
    private String url;
    /**
     * Whether to verify SSL certificates when connecting to CyberArk Conjur
     */
    private Boolean verifySsl = true;
    /**
     * Whether autowiring is enabled. This is used for automatic autowiring
     * options (the option must be marked as autowired) by looking up in the
     * registry to find if there is a single instance of matching type, which
     * then gets configured on the component. This can be used for automatic
     * configuring JDBC data sources, JMS connection factories, AWS Clients,
     * etc.
     */
    private Boolean autowiredEnabled = true;
    /**
     * The API key for authentication with CyberArk Conjur
     */
    private String apiKey;
    /**
     * Pre-authenticated token to use for CyberArk Conjur
     */
    private String authToken;
    /**
     * The password for authentication with CyberArk Conjur
     */
    private String password;
    /**
     * The username for authentication with CyberArk Conjur
     */
    private String username;

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getCertificatePath() {
        return certificatePath;
    }

    public void setCertificatePath(String certificatePath) {
        this.certificatePath = certificatePath;
    }

    public CyberArkVaultConfiguration getConfiguration() {
        return configuration;
    }

    public void setConfiguration(CyberArkVaultConfiguration configuration) {
        this.configuration = configuration;
    }

    public ConjurClient getConjurClient() {
        return conjurClient;
    }

    public void setConjurClient(ConjurClient conjurClient) {
        this.conjurClient = conjurClient;
    }

    public Boolean getLazyStartProducer() {
        return lazyStartProducer;
    }

    public void setLazyStartProducer(Boolean lazyStartProducer) {
        this.lazyStartProducer = lazyStartProducer;
    }

    public String getSecretId() {
        return secretId;
    }

    public void setSecretId(String secretId) {
        this.secretId = secretId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Boolean getVerifySsl() {
        return verifySsl;
    }

    public void setVerifySsl(Boolean verifySsl) {
        this.verifySsl = verifySsl;
    }

    public Boolean getAutowiredEnabled() {
        return autowiredEnabled;
    }

    public void setAutowiredEnabled(Boolean autowiredEnabled) {
        this.autowiredEnabled = autowiredEnabled;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public String getAuthToken() {
        return authToken;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}