CaffeineAggregationRepository
CaffeineIdempotentRepository
CaffeineKeyValueRepository
CassandraAggregationRepository
CassandraIdempotentRepository
ConsulClusterService
CronScheduledRoutePolicy
EhcacheAggregationRepository
EhcacheIdempotentRepository
EhcacheKeyValueRepository
ElasticsearchBulkRequestAggregationStrategy
Etcd3AggregationRepository
FileLockClusterService
HazelcastAggregationRepository
HazelcastIdempotentRepository
HazelcastKeyValueRepository
InfinispanEmbeddedAggregationRepository
InfinispanEmbeddedClusterService
InfinispanEmbeddedIdempotentRepository
InfinispanRemoteAggregationRepository
InfinispanRemoteClusterService
InfinispanRemoteIdempotentRepository
InfinispanRemoteKeyValueRepository
JCacheAggregationRepository
JCacheIdempotentRepository
JCacheKeyValueRepository
JGroupsRaftClusterService
JdbcAggregationRepository
JdbcMessageIdRepository
KafkaIdempotentRepository
KubernetesClusterService
LoggingHttpActivityListener
MongoDbIdempotentRepository
OpensearchBulkRequestAggregationStrategy
SimpleScheduledRoutePolicy
SpringCacheIdempotentRepository
SpringRedisIdempotentRepository
TarAggregationStrategy
XsltAggregationStrategy
XsltSaxonAggregationStrategy
ZipAggregationStrategy
ZooKeeperClusterService