#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Sync Camel Spring Boot Master Branch

on:
  schedule:
    # Run every 10 minutes
    - cron:  '10 * * * *'
jobs:
  build:
    name: Sync Camel Spring Boot Master Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: apache/camel
          ref: master
          path: camel
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project
        run: ./mvnw -V --no-transfer-progress clean install -DskipTests
        working-directory: /home/runner/work/camel-spring-boot/camel
      - name: Checkout
        uses: actions/checkout@v1
        with:
          path: camel-spring-boot
          fetch-depth: 0
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project
        run: ./mvnw -V --no-transfer-progress clean install -DskipTests
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch:
          title: '[Github Actions] Periodic Sync Camel Spring Boot Master Branch'
          body: |
            Periodic Sync of Camel Spring Boot Master Branch with main Camel Master.
            see https://github.com/apache/camel-spring-boot/blob/master/.github/workflows/automatic-sync-master.yml
